-- Auto-generated by scripts/generate-seed.ts. Do not edit by hand.
-- Seeds the public.recipes table with the SwipeBite mock catalogue.

set check_function_bodies = off;

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Mercimek Çorbası', 'Klasik, sıcacık ve ev hissi veren kırmızı mercimek çorbası.', 'https://images.unsplash.com/photo-1547592180-85f173990554?w=1200', 30, 'kolay',
       4, '[{"name":"kırmızı mercimek","quantity":"1 su bardağı"},{"name":"soğan","quantity":"1 adet"},{"name":"havuç","quantity":"1 adet"},{"name":"patates","quantity":"1 adet"},{"name":"tereyağı","quantity":"1 yemek kaşığı"},{"name":"kırmızı toz biber","quantity":"1 tatlı kaşığı"},{"name":"tuz","quantity":"tadında"}]'::jsonb, ARRAY['Soğan, havuç ve patatesi küçük doğra.', 'Tencerede tereyağında soğanı pembeleştir.', 'Mercimek ve sebzeleri ekle, üzerine sıcak su koy.', 'Yumuşayana kadar 25 dk kısık ateşte pişir.', 'Blendırdan geçir, üzerine kızdırılmış toz biberli yağ gez.'], ARRAY['çorba', 'vejetaryen', 'pratik'], 'Türk'
where not exists (select 1 from public.recipes where title = 'Mercimek Çorbası');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Kuru Fasulye', 'Pilav üstü kuru fasulye — kalabalık sofraların vazgeçilmezi.', 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=1200', 60, 'orta',
       4, '[{"name":"kuru fasulye","quantity":"2 su bardağı"},{"name":"soğan","quantity":"1 adet"},{"name":"salça","quantity":"1 yemek kaşığı"},{"name":"sucuk","quantity":"opsiyonel"},{"name":"zeytinyağı","quantity":"3 yemek kaşığı"}]'::jsonb, ARRAY['Fasulyeleri bir gece önceden ıslat.', 'Soğanı yağda kavur, salçayı ekle.', 'Süzülmüş fasulyeyi ve sıcak suyu ekle.', 'Yumuşayana kadar 45 dk pişir.', 'Pilavla servis et.'], ARRAY['ana yemek', 'aile', 'klasik'], 'Türk'
where not exists (select 1 from public.recipes where title = 'Kuru Fasulye');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Tavuk Sote', 'Renkli biberlerle hızlı bir akşam yemeği.', 'https://images.unsplash.com/photo-1604908554007-b0db4cce6dba?w=1200', 25, 'kolay',
       3, '[{"name":"tavuk göğsü","quantity":"500 g"},{"name":"kırmızı biber","quantity":"1 adet"},{"name":"yeşil biber","quantity":"1 adet"},{"name":"soğan","quantity":"1 adet"},{"name":"domates","quantity":"2 adet"},{"name":"zeytinyağı","quantity":"2 yk"}]'::jsonb, ARRAY['Tavuğu kuşbaşı doğrayıp yağda mühürle.', 'Soğan ve biberleri ekle, 5 dk sote et.', 'Doğranmış domatesi ekle, suyunu çekene kadar pişir.', 'Tuz, karabiber ve maydanozla servis et.'], ARRAY['ana yemek', 'tavuk', 'pratik'], 'Türk'
where not exists (select 1 from public.recipes where title = 'Tavuk Sote');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Menemen', 'Kahvaltının ya da geç bir akşamın kurtarıcısı.', 'https://images.unsplash.com/photo-1606756790138-261d2b21cd75?w=1200', 15, 'kolay',
       2, '[{"name":"yumurta","quantity":"4 adet"},{"name":"domates","quantity":"2 adet"},{"name":"sivri biber","quantity":"2 adet"},{"name":"tereyağı","quantity":"1 yk"}]'::jsonb, ARRAY['Biberleri tereyağında kavur.', 'Soyulmuş domatesi ekle, suyunu çekene kadar pişir.', 'Yumurtaları kır, yavaşça karıştır.', 'Tuz ve karabiberle servis et.'], ARRAY['kahvaltı', 'vejetaryen', 'pratik'], 'Türk'
where not exists (select 1 from public.recipes where title = 'Menemen');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Tereyağlı Makarna', 'Hızlı, doyurucu ve herkesin sevdiği klasik.', 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=1200', 15, 'kolay',
       2, '[{"name":"makarna","quantity":"250 g"},{"name":"tereyağı","quantity":"2 yk"},{"name":"kaşar peyniri","quantity":"rendelenmiş"}]'::jsonb, ARRAY['Makarnayı tuzlu suda haşla.', 'Süzdükten sonra tereyağıyla harmanla.', 'Üzerine rendelenmiş kaşar serp.'], ARRAY['ana yemek', 'pratik', 'çocuk dostu'], 'İtalyan-Türk'
where not exists (select 1 from public.recipes where title = 'Tereyağlı Makarna');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Fırında Köfte Patates', 'Tek tepside aile yemeği.', 'https://images.unsplash.com/photo-1565895405138-6c3a1555da6a?w=1200', 50, 'orta',
       4, '[{"name":"kıyma","quantity":"500 g"},{"name":"patates","quantity":"3 adet"},{"name":"domates","quantity":"2 adet"},{"name":"biber","quantity":"2 adet"},{"name":"salça","quantity":"1 yk"}]'::jsonb, ARRAY['Kıymayı baharatla yoğur, köfte şekli ver.', 'Sebzeleri ve köfteleri tepsiye diz.', 'Salçalı sıcak suyu üzerine dök.', '180°C fırında 40 dk pişir.'], ARRAY['ana yemek', 'aile', 'fırın'], 'Türk'
where not exists (select 1 from public.recipes where title = 'Fırında Köfte Patates');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Yayla Çorbası', 'Yoğurtlu, naneli, ferah bir çorba.', 'https://images.unsplash.com/photo-1607330289024-1535c6b4e1c1?w=1200', 30, 'kolay',
       4, '[{"name":"yoğurt","quantity":"2 su bardağı"},{"name":"pirinç","quantity":"1/2 su bardağı"},{"name":"yumurta sarısı","quantity":"1 adet"},{"name":"kuru nane","quantity":"1 tk"},{"name":"tereyağı","quantity":"1 yk"}]'::jsonb, ARRAY['Pirinci suda haşla.', 'Yoğurt, un ve yumurtayı çırp, çorbaya temperle.', 'Üzerine naneli tereyağı gez.'], ARRAY['çorba', 'vejetaryen'], 'Türk'
where not exists (select 1 from public.recipes where title = 'Yayla Çorbası');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Kabak Mücver', 'Yoğurtla muhteşem, hafif bir akşam yemeği.', 'https://images.unsplash.com/photo-1604908177522-401b1c364c5b?w=1200', 25, 'kolay',
       3, '[{"name":"kabak","quantity":"2 adet"},{"name":"yumurta","quantity":"2 adet"},{"name":"un","quantity":"3 yk"},{"name":"beyaz peynir","quantity":"100 g"},{"name":"dereotu","quantity":"bir tutam"}]'::jsonb, ARRAY['Kabağı rendele, suyunu sık.', 'Tüm malzemeleri karıştır.', 'Kaşıkla yağa al, kızart.'], ARRAY['vejetaryen', 'hafif'], 'Türk'
where not exists (select 1 from public.recipes where title = 'Kabak Mücver');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Zeytinyağlı Taze Fasulye', 'Soğuk servis edilen, ferah bir klasik.', 'https://images.unsplash.com/photo-1604908554007-1c1f1d7b9e7f?w=1200', 40, 'kolay',
       4, '[{"name":"taze fasulye","quantity":"500 g"},{"name":"soğan","quantity":"1 adet"},{"name":"domates","quantity":"1 adet"},{"name":"zeytinyağı","quantity":"4 yk"},{"name":"şeker","quantity":"1 tk"}]'::jsonb, ARRAY['Soğanı yağda kavur.', 'Fasulyeyi ekle, kısaca çevir.', 'Domates, şeker ve sıcak su ekle.', 'Kısık ateşte yumuşayana kadar pişir, soğuk servis et.'], ARRAY['zeytinyağlı', 'vejetaryen', 'hafif'], 'Türk'
where not exists (select 1 from public.recipes where title = 'Zeytinyağlı Taze Fasulye');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Tereyağlı Şehriyeli Pilav', 'Her yemeğin yanına yakışan klasik.', 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=1200', 25, 'kolay',
       4, '[{"name":"pirinç","quantity":"2 su bardağı"},{"name":"tel şehriye","quantity":"1/2 su bardağı"},{"name":"tereyağı","quantity":"2 yk"},{"name":"tuz","quantity":"1 tk"}]'::jsonb, ARRAY['Şehriyeyi tereyağında pembeleştir.', 'Yıkanmış pirinci ekle, kısaca kavur.', 'Sıcak suyu ekle, tuzla, kapağı kapatıp kısık ateşte pişir.', '10 dk demlendir.'], ARRAY['yan yemek', 'klasik'], 'Türk'
where not exists (select 1 from public.recipes where title = 'Tereyağlı Şehriyeli Pilav');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Sucuklu Yumurta', 'Kahvaltıların kralı.', 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=1200', 10, 'kolay',
       2, '[{"name":"sucuk","quantity":"6 dilim"},{"name":"yumurta","quantity":"3 adet"},{"name":"tereyağı","quantity":"1 tk"}]'::jsonb, ARRAY['Sucukları sahanda kızart.', 'Yumurtaları kır, sarısı akışkan kalacak şekilde pişir.'], ARRAY['kahvaltı', 'pratik'], 'Türk'
where not exists (select 1 from public.recipes where title = 'Sucuklu Yumurta');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'İmam Bayıldı', 'Zeytinyağlı, doyurucu, ev sofrasının ışığı.', 'https://images.unsplash.com/photo-1626078297007-1e8b3a5c79b1?w=1200', 55, 'orta',
       4, '[{"name":"patlıcan","quantity":"4 adet"},{"name":"soğan","quantity":"2 adet"},{"name":"domates","quantity":"2 adet"},{"name":"sarımsak","quantity":"4 diş"},{"name":"zeytinyağı","quantity":"5 yk"}]'::jsonb, ARRAY['Patlıcanları alaca soyup tuzlu suda beklet.', 'İç harcı için soğan, sarımsak ve domatesi pişir.', 'Patlıcanları hafif kızart, içini doldur.', 'Tencerede zeytinyağı ve suyla 30 dk pişir.'], ARRAY['zeytinyağlı', 'vejetaryen'], 'Türk'
where not exists (select 1 from public.recipes where title = 'İmam Bayıldı');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Mantarlı Milföy Tart', 'Çıtır milföy üzerinde mantarlı, aromatik ve pratik bir fırın lezzeti.', 'https://images.unsplash.com/photo-1565299543923-37dd37887442?w=1200', 45, 'orta',
       4, '[{"name":"milföy","quantity":"9 adet"},{"name":"mantar","quantity":"400 gr"},{"name":"soğan","quantity":"2 adet"},{"name":"tereyağı","quantity":"2 yk"},{"name":"yumurta sarısı","quantity":"1 adet"}]'::jsonb, ARRAY['Mantar ve soğanı tavada sotele.', 'Milföyleri fırın tepsisine yerleştir.', 'Mantarlı harcı milföyün üzerine yay.', 'Üzerini yumurta sarısıyla fırçala ve kızarana kadar pişir.'], ARRAY['hamurlu', 'fırın', 'vejetaryen', 'mantar'], 'Türk'
where not exists (select 1 from public.recipes where title = 'Mantarlı Milföy Tart');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Zeytinyağlı Kabak Sıyırma', 'Hafif, ferah ve yaz sofralarına uygun zeytinyağlı kabak yemeği.', 'https://images.unsplash.com/photo-1598511757337-fe2cafc31ba0?w=1200', 35, 'kolay',
       4, '[{"name":"kabak","quantity":"2 adet"},{"name":"soğan","quantity":"1 adet"},{"name":"pirinç","quantity":"1/4 su bardağı"},{"name":"zeytinyağı","quantity":"1 su bardağı"},{"name":"limon","quantity":"1 adet"}]'::jsonb, ARRAY['Soğanı zeytinyağında yumuşayana kadar pişir.', 'Pirinci ekleyip kısa süre çevir.', 'İnce doğranmış kabakları ekle.', 'Limon suyu ve yeşilliklerle tamamlayıp soğuk servis et.'], ARRAY['zeytinyağlı', 'vejetaryen', 'hafif', 'sebze'], 'Türk'
where not exists (select 1 from public.recipes where title = 'Zeytinyağlı Kabak Sıyırma');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Girit Ezmeli Börek', 'Peynirli ve fesleğenli iç harcıyla doyurucu, özel sofralık bir börek.', 'https://images.unsplash.com/photo-1612392061787-2d078b3e573d?w=1200', 60, 'orta',
       6, '[{"name":"yufka","quantity":"3 adet"},{"name":"yoğurt","quantity":"1 su bardağı"},{"name":"zeytinyağı","quantity":"1/2 su bardağı"},{"name":"beyaz peynir","quantity":"250 gr"},{"name":"lor peyniri","quantity":"250 gr"}]'::jsonb, ARRAY['Peynirleri ezip yeşilliklerle karıştır.', 'Yufkaları soslayarak üst üste diz.', 'İç harcı yayıp böreği şekillendir.', 'Fırında üzeri kızarana kadar pişir.'], ARRAY['börek', 'hamurlu', 'peynirli', 'kahvaltı'], 'Türk'
where not exists (select 1 from public.recipes where title = 'Girit Ezmeli Börek');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Bademli Kabak Tarator', 'Yoğurtlu, kabaklı ve bademli ferah bir meze alternatifi.', 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=1200', 25, 'kolay',
       4, '[{"name":"kabak","quantity":"2 adet"},{"name":"süzme yoğurt","quantity":"1.5 su bardağı"},{"name":"sarımsak","quantity":"1 diş"},{"name":"zeytinyağı","quantity":"2 yk"},{"name":"file badem","quantity":"1 avuç"}]'::jsonb, ARRAY['Kabakları rendeleyip tavada sotele.', 'Yoğurt, sarımsak ve tuzu karıştır.', 'Soğuyan kabağı yoğurtlu karışıma ekle.', 'Üzerine kavrulmuş badem serpip servis et.'], ARRAY['meze', 'yoğurtlu', 'vejetaryen', 'hafif'], 'Türk'
where not exists (select 1 from public.recipes where title = 'Bademli Kabak Tarator');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Çilekli Semizotu Salatası', 'Tatlı-ekşi dengesiyle farklı, ferah ve hafif bir salata.', 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=1200', 15, 'kolay',
       4, '[{"name":"semizotu","quantity":"2 bağ"},{"name":"çilek","quantity":"10 adet"},{"name":"ceviz","quantity":"1 su bardağı"},{"name":"zeytinyağı","quantity":"6 yk"},{"name":"limon suyu","quantity":"1/4 limon"}]'::jsonb, ARRAY['Semizotunu ayıklayıp yıka.', 'Çilekleri dilimle, cevizi iri parçala.', 'Sos malzemelerini karıştır.', 'Tüm malzemeleri harmanlayıp servis et.'], ARRAY['salata', 'hafif', 'vejetaryen', 'pratik'], 'Türk'
where not exists (select 1 from public.recipes where title = 'Çilekli Semizotu Salatası');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Beef Wellington', 'Milföy kaplı bonfileyle hazırlanan gösterişli ve özel günlere uygun bir ana yemek.', 'https://images.unsplash.com/photo-1558030006-450675393462?w=1200', 90, 'zor',
       4, '[{"name":"bonfile","quantity":"700 gr"},{"name":"milföy","quantity":"5 adet"},{"name":"mantar","quantity":"10 adet"},{"name":"sarımsak","quantity":"2 diş"},{"name":"yumurta sarısı","quantity":"1 adet"}]'::jsonb, ARRAY['Bonfileyi tavada mühürle.', 'Mantar harcını hazırlayıp soğut.', 'Eti milföy ve mantarlı harçla sar.', 'Üzerini yumurta sarısıyla fırçala ve fırında pişir.'], ARRAY['et', 'özel gün', 'fırın', 'dünya mutfağı'], 'İngiliz'
where not exists (select 1 from public.recipes where title = 'Beef Wellington');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Çikolata Mus Tiramisu', 'Kahve ve çikolata sevenler için yoğun aromalı, katmanlı bir tatlı.', 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=1200', 50, 'orta',
       6, '[{"name":"kedidili","quantity":"1 paket"},{"name":"granül kahve","quantity":"2 yk"},{"name":"bitter çikolata","quantity":"290 gr"},{"name":"yumurta","quantity":"4 adet"},{"name":"krema","quantity":"1 su bardağı"}]'::jsonb, ARRAY['Kahveli karışımı hazırla.', 'Çikolatalı mus katmanını hazırla.', 'Kedidillerini kahveyle ıslat.', 'Katmanları oluşturup buzdolabında dinlendir.'], ARRAY['tatlı', 'çikolatalı', 'kahveli', 'özel gün'], 'İtalyan'
where not exists (select 1 from public.recipes where title = 'Çikolata Mus Tiramisu');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'İsveç Keki - Kladdkaka', 'Dışı hafif pişmiş, içi yoğun çikolatalı pratik bir kek.', 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=1200', 40, 'orta',
       6, '[{"name":"tereyağı","quantity":"200 gr"},{"name":"bitter çikolata","quantity":"200 gr"},{"name":"toz şeker","quantity":"250 gr"},{"name":"yumurta","quantity":"4 adet"},{"name":"un","quantity":"40 gr"}]'::jsonb, ARRAY['Tereyağı ve çikolatayı erit.', 'Yumurta ve şekeri karıştır.', 'Unu ekleyip kısa süre karıştır.', 'Kalıba alıp içi hafif nemli kalacak şekilde pişir.'], ARRAY['tatlı', 'kek', 'çikolatalı', 'dünya mutfağı'], 'İsveç'
where not exists (select 1 from public.recipes where title = 'İsveç Keki - Kladdkaka');

insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select 'Muzlu Ters Yüz Pasta', 'Karamelli muz tabanı ve yumuşak kek dokusuyla keyifli bir ev tatlısı.', 'https://images.unsplash.com/photo-1606101273945-e9eba91c0dc4?w=1200', 65, 'orta',
       8, '[{"name":"muz","quantity":"7 adet"},{"name":"toz şeker","quantity":"1 su bardağı"},{"name":"tereyağı","quantity":"125 gr"},{"name":"yumurta","quantity":"2 adet"},{"name":"un","quantity":"2 su bardağı"}]'::jsonb, ARRAY['Karamel tabanı hazırla.', 'Muzları kalıba diz.', 'Kek harcını karıştır.', 'Harcı muzların üzerine döküp fırında pişir.'], ARRAY['tatlı', 'kek', 'muzlu', 'comfort_food'], 'Dünya'
where not exists (select 1 from public.recipes where title = 'Muzlu Ters Yüz Pasta');
