/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        bg: "#FAF7F2",
        card: "#FFFFFF",
        cream: "#F0EBE3",
        muted: "#EDE8E1",
        border: "#E8E3DC",
        ink: "#1A1714",
        graphite: "#3D3530",
        slate: "#6B6560",
        dim: "#9E9890",
        hairline: "#C8C0B8",
        primary: "#F0B429",
        "primary-deep": "#D4A017",
        "primary-soft": "#FFF8E7",
        accent: "#E07A5F",
        "accent-soft": "#FBE6DE",
        forest: "#4A7A50",
        "forest-soft": "#EEF4EE",
        success: "#4A7A50",
        danger: "#DC2626",
        like: "#4A7A50",
        nope: "#DC2626",
        superlike: "#3B82F6",
        canvas: "#FAF7F2",
        snow: "#FFFFFF",
        cloud: "#F0EBE3",
      },
      fontFamily: {
        sans: ["Inter_400Regular", "system-ui", "sans-serif"],
        serif: ["Fraunces_700Bold", "Georgia", "serif"],
      },
      borderRadius: {
        sm: "10px",
        md: "14px",
        card: "22px",
        hero: "24px",
        btn: "16px",
        pill: "999px",
      },
      spacing: {
        gutter: "24px",
      },
    },
  },
  plugins: [],
};
