import { Recipe } from "@/types/domain";

/**
 * AI-generated Turkish recipes.
 * AUTO-GENERATED by scripts/generate-recipes-ai.ts. Do not edit by hand.
 *
 * Run `npx tsx scripts/generate-recipes-ai.ts --count 50 --category aksam` to add more.
 * The script APPENDS, deduping by slug.
 */
export const AI_GENERATED_RECIPES: Recipe[] = [];
