// AUTO-GENERATED by scripts/import-cocktail-content-en.ts
// Source: cocktail_app_content_english_500.xlsx
// Do not edit by hand — re-run the import to refresh.
import type { BarIngredient, BarIngredientCategory } from "@/types/bar";

export const BAR_INGREDIENTS: BarIngredient[] = [
  {
    "id": "spirit-applejack",
    "name": "Applejack",
    "category": "spirits",
    "emoji": "🍎",
    "altName": "American apple brandy"
  },
  {
    "id": "spirit-bourbon",
    "name": "Bourbon",
    "category": "spirits",
    "emoji": "🥃",
    "altName": "American whiskey",
    "essential": true
  },
  {
    "id": "spirit-brandy",
    "name": "Brandy",
    "category": "spirits",
    "emoji": "🍇",
    "altName": "Grape brandy"
  },
  {
    "id": "spirit-cachaca",
    "name": "Cachaça",
    "category": "spirits",
    "emoji": "🟢",
    "altName": "Brazilian sugarcane spirit"
  },
  {
    "id": "spirit-calvados",
    "name": "Calvados",
    "category": "spirits",
    "emoji": "🍏",
    "altName": "French apple brandy"
  },
  {
    "id": "spirit-cognac",
    "name": "Cognac",
    "category": "spirits",
    "emoji": "🍷",
    "altName": "French brandy"
  },
  {
    "id": "spirit-genever",
    "name": "Genever",
    "category": "spirits",
    "emoji": "🌾",
    "altName": "Dutch malted gin"
  },
  {
    "id": "spirit-gin",
    "name": "Gin",
    "category": "spirits",
    "emoji": "🌿",
    "altName": "London Dry Gin",
    "essential": true
  },
  {
    "id": "spirit-irish-whiskey",
    "name": "Irish Whiskey",
    "category": "spirits",
    "emoji": "☘️",
    "altName": "Irish whiskey"
  },
  {
    "id": "spirit-japanese-whisky",
    "name": "Japanese Whisky",
    "category": "spirits",
    "emoji": "🍵",
    "altName": "Japanese whisky"
  },
  {
    "id": "spirit-mezcal",
    "name": "Mezcal",
    "category": "spirits",
    "emoji": "🌵",
    "altName": "Smoky agave spirit"
  },
  {
    "id": "spirit-pisco",
    "name": "Pisco",
    "category": "spirits",
    "emoji": "🍇",
    "altName": "Grape brandy"
  },
  {
    "id": "spirit-rum-aged",
    "name": "Aged Rum",
    "category": "spirits",
    "emoji": "🥃",
    "altName": "Amber rum"
  },
  {
    "id": "spirit-rum-dark",
    "name": "Dark Rum",
    "category": "spirits",
    "emoji": "🌴",
    "altName": "Black or dark rum",
    "essential": true
  },
  {
    "id": "spirit-rum-overproof",
    "name": "Overproof Rum",
    "category": "spirits",
    "emoji": "🔥",
    "altName": "High-proof rum"
  },
  {
    "id": "spirit-rum-white",
    "name": "White Rum",
    "category": "spirits",
    "emoji": "🥥",
    "altName": "Light rum",
    "essential": true
  },
  {
    "id": "spirit-rye",
    "name": "Rye Whiskey",
    "category": "spirits",
    "emoji": "🌾",
    "altName": "American rye",
    "essential": true
  },
  {
    "id": "spirit-scotch",
    "name": "Scotch Whisky",
    "category": "spirits",
    "emoji": "🏴",
    "altName": "Scotch"
  },
  {
    "id": "spirit-scotch-blended",
    "name": "Blended Scotch",
    "category": "spirits",
    "emoji": "🏴",
    "altName": "Blended Scotch whisky"
  },
  {
    "id": "spirit-scotch-peated",
    "name": "Peated Scotch",
    "category": "spirits",
    "emoji": "💨",
    "altName": "Smoky Scotch whisky"
  },
  {
    "id": "spirit-tequila-blanco",
    "name": "Tequila Blanco",
    "category": "spirits",
    "emoji": "🌵",
    "altName": "Silver tequila",
    "essential": true
  },
  {
    "id": "spirit-tequila-reposado",
    "name": "Tequila Reposado",
    "category": "spirits",
    "emoji": "🌵",
    "altName": "Aged tequila"
  },
  {
    "id": "spirit-vodka",
    "name": "Vodka",
    "category": "spirits",
    "emoji": "🍶",
    "altName": "Neutral grain spirit",
    "essential": true
  },
  {
    "id": "spirit-vodka-citron",
    "name": "Citron Vodka",
    "category": "spirits",
    "emoji": "🍋",
    "altName": "Lemon-flavored vodka"
  },
  {
    "id": "spirit-vodka-vanilla",
    "name": "Vanilla Vodka",
    "category": "spirits",
    "emoji": "🌼",
    "altName": "Vanilla-flavored vodka"
  },
  {
    "id": "liqueur-absinthe",
    "name": "Absinthe",
    "category": "liqueur-vermouth",
    "emoji": "🟢",
    "altName": "Anise spirit"
  },
  {
    "id": "liqueur-amaretto",
    "name": "Amaretto",
    "category": "liqueur-vermouth",
    "emoji": "🌰",
    "altName": "Almond liqueur"
  },
  {
    "id": "liqueur-aperol",
    "name": "Aperol",
    "category": "liqueur-vermouth",
    "emoji": "🧡",
    "altName": "Bitter orange aperitif"
  },
  {
    "id": "liqueur-apricot-brandy",
    "name": "Apricot Brandy",
    "category": "liqueur-vermouth",
    "emoji": "🍑",
    "altName": "Apricot liqueur"
  },
  {
    "id": "liqueur-banana",
    "name": "Banana Liqueur",
    "category": "liqueur-vermouth",
    "emoji": "🍌",
    "altName": "Banana liqueur"
  },
  {
    "id": "liqueur-benedictine",
    "name": "Bénédictine",
    "category": "liqueur-vermouth",
    "emoji": "🌿",
    "altName": "Herbal liqueur"
  },
  {
    "id": "liqueur-blue-curacao",
    "name": "Blue Curaçao",
    "category": "liqueur-vermouth",
    "emoji": "🔵",
    "altName": "Blue orange liqueur"
  },
  {
    "id": "liqueur-campari",
    "name": "Campari",
    "category": "liqueur-vermouth",
    "emoji": "❤️",
    "altName": "Bitter red aperitif",
    "essential": true
  },
  {
    "id": "liqueur-chambord",
    "name": "Chambord",
    "category": "liqueur-vermouth",
    "emoji": "🩷",
    "altName": "Raspberry liqueur"
  },
  {
    "id": "liqueur-chartreuse-green",
    "name": "Green Chartreuse",
    "category": "liqueur-vermouth",
    "emoji": "💚",
    "altName": "Herbal liqueur"
  },
  {
    "id": "liqueur-chartreuse-yellow",
    "name": "Yellow Chartreuse",
    "category": "liqueur-vermouth",
    "emoji": "💛",
    "altName": "Herbal liqueur"
  },
  {
    "id": "liqueur-cherry-heering",
    "name": "Cherry Heering",
    "category": "liqueur-vermouth",
    "emoji": "🍒",
    "altName": "Cherry liqueur"
  },
  {
    "id": "liqueur-coconut",
    "name": "Coconut Liqueur",
    "category": "liqueur-vermouth",
    "emoji": "🥥",
    "altName": "Malibu-style"
  },
  {
    "id": "liqueur-coffee",
    "name": "Coffee Liqueur",
    "category": "liqueur-vermouth",
    "emoji": "☕",
    "altName": "Kahlúa-style"
  },
  {
    "id": "liqueur-creme-de-cacao-dark",
    "name": "Dark Crème de Cacao",
    "category": "liqueur-vermouth",
    "emoji": "🍫",
    "altName": "Chocolate liqueur"
  },
  {
    "id": "liqueur-creme-de-cacao-white",
    "name": "White Crème de Cacao",
    "category": "liqueur-vermouth",
    "emoji": "🍫",
    "altName": "Clear chocolate liqueur"
  },
  {
    "id": "liqueur-creme-de-cassis",
    "name": "Crème de Cassis",
    "category": "liqueur-vermouth",
    "emoji": "🫐",
    "altName": "Blackcurrant liqueur"
  },
  {
    "id": "liqueur-creme-de-menthe-green",
    "name": "Green Crème de Menthe",
    "category": "liqueur-vermouth",
    "emoji": "🌿",
    "altName": "Mint liqueur"
  },
  {
    "id": "liqueur-creme-de-menthe-white",
    "name": "White Crème de Menthe",
    "category": "liqueur-vermouth",
    "emoji": "🌿",
    "altName": "Clear mint liqueur"
  },
  {
    "id": "liqueur-creme-de-mure",
    "name": "Crème de Mûre",
    "category": "liqueur-vermouth",
    "emoji": "🫐",
    "altName": "Blackberry liqueur"
  },
  {
    "id": "liqueur-creme-de-violette",
    "name": "Crème de Violette",
    "category": "liqueur-vermouth",
    "emoji": "💜",
    "altName": "Violet liqueur"
  },
  {
    "id": "liqueur-drambuie",
    "name": "Drambuie",
    "category": "liqueur-vermouth",
    "emoji": "🍯",
    "altName": "Scotch honey liqueur"
  },
  {
    "id": "liqueur-elderflower",
    "name": "Elderflower Liqueur",
    "category": "liqueur-vermouth",
    "emoji": "🌸",
    "altName": "St-Germain-style"
  },
  {
    "id": "liqueur-lillet-blanc",
    "name": "Lillet Blanc",
    "category": "liqueur-vermouth",
    "emoji": "🥂",
    "altName": "Aromatized wine"
  },
  {
    "id": "liqueur-maraschino",
    "name": "Maraschino Liqueur",
    "category": "liqueur-vermouth",
    "emoji": "🍒",
    "altName": "Dry cherry liqueur"
  },
  {
    "id": "liqueur-orange",
    "name": "Orange Liqueur",
    "category": "liqueur-vermouth",
    "emoji": "🍊",
    "altName": "Cointreau / Triple Sec / Curaçao",
    "essential": true
  },
  {
    "id": "liqueur-passionfruit",
    "name": "Passion Fruit Liqueur",
    "category": "liqueur-vermouth",
    "emoji": "🟡",
    "altName": "Passoã-style"
  },
  {
    "id": "liqueur-peach",
    "name": "Peach Schnapps",
    "category": "liqueur-vermouth",
    "emoji": "🍑",
    "altName": "Peach liqueur"
  },
  {
    "id": "liqueur-pimento-dram",
    "name": "Pimento Dram",
    "category": "liqueur-vermouth",
    "emoji": "🌶️",
    "altName": "Allspice liqueur"
  },
  {
    "id": "liqueur-pimms-no1",
    "name": "Pimm's No. 1",
    "category": "liqueur-vermouth",
    "emoji": "🍓",
    "altName": "Gin-based fruit cup"
  },
  {
    "id": "liqueur-suze",
    "name": "Gentian Aperitif",
    "category": "liqueur-vermouth",
    "emoji": "🌼",
    "altName": "Gentian bitter aperitif"
  },
  {
    "id": "liqueur-vanilla",
    "name": "Vanilla Liqueur",
    "category": "liqueur-vermouth",
    "emoji": "🍦",
    "altName": "Vanilla liqueur"
  },
  {
    "id": "liqueur-vermouth-dry",
    "name": "Dry Vermouth",
    "category": "liqueur-vermouth",
    "emoji": "🥂",
    "altName": "French dry vermouth",
    "essential": true
  },
  {
    "id": "liqueur-vermouth-sweet",
    "name": "Sweet Vermouth",
    "category": "liqueur-vermouth",
    "emoji": "🍷",
    "altName": "Red vermouth",
    "essential": true
  },
  {
    "id": "amaro-cio-ciaro",
    "name": "CioCiaro",
    "category": "amaro-bitters",
    "emoji": "🟤",
    "altName": "Italian amaro"
  },
  {
    "id": "amaro-cynar",
    "name": "Cynar",
    "category": "amaro-bitters",
    "emoji": "🌿",
    "altName": "Artichoke amaro"
  },
  {
    "id": "amaro-fernet-branca",
    "name": "Fernet-Branca",
    "category": "amaro-bitters",
    "emoji": "🌿",
    "altName": "Bitter herbal amaro"
  },
  {
    "id": "amaro-montenegro",
    "name": "Amaro Montenegro",
    "category": "amaro-bitters",
    "emoji": "🟠",
    "altName": "Italian amaro"
  },
  {
    "id": "amaro-nonino",
    "name": "Amaro Nonino",
    "category": "amaro-bitters",
    "emoji": "🟤",
    "altName": "Italian amaro"
  },
  {
    "id": "wine-champagne",
    "name": "Champagne",
    "category": "wine-sparkling",
    "emoji": "🍾",
    "altName": "Dry Champagne"
  },
  {
    "id": "wine-port-ruby",
    "name": "Ruby Port",
    "category": "wine-sparkling",
    "emoji": "🍷",
    "altName": "Sweet fortified wine"
  },
  {
    "id": "wine-prosecco",
    "name": "Prosecco",
    "category": "wine-sparkling",
    "emoji": "🥂",
    "altName": "Italian sparkling wine",
    "essential": true
  },
  {
    "id": "wine-rose",
    "name": "Rosé Wine",
    "category": "wine-sparkling",
    "emoji": "🌸",
    "altName": "Dry rosé"
  },
  {
    "id": "wine-sake",
    "name": "Sake",
    "category": "wine-sparkling",
    "emoji": "🍶",
    "altName": "Japanese rice wine"
  },
  {
    "id": "wine-sherry-amontillado",
    "name": "Amontillado Sherry",
    "category": "wine-sparkling",
    "emoji": "🍷",
    "altName": "Nutty dry sherry"
  },
  {
    "id": "wine-sherry-fino",
    "name": "Fino Sherry",
    "category": "wine-sparkling",
    "emoji": "🍷",
    "altName": "Dry sherry"
  },
  {
    "id": "wine-vermouth-blanc",
    "name": "Blanc Vermouth",
    "category": "wine-sparkling",
    "emoji": "🥂",
    "altName": "White sweet vermouth"
  },
  {
    "id": "wine-white",
    "name": "Dry White Wine",
    "category": "wine-sparkling",
    "emoji": "🥂",
    "altName": "Dry white wine"
  },
  {
    "id": "mixer-apple-cider",
    "name": "Apple Cider",
    "category": "mixer",
    "emoji": "🍎",
    "altName": "Unfiltered apple juice"
  },
  {
    "id": "mixer-coconut-cream",
    "name": "Cream of Coconut",
    "category": "mixer",
    "emoji": "🥥",
    "altName": "Sweetened coconut cream"
  },
  {
    "id": "mixer-cola",
    "name": "Cola",
    "category": "mixer",
    "emoji": "🥤",
    "altName": "Cola soda"
  },
  {
    "id": "mixer-cold-brew",
    "name": "Cold Brew Coffee",
    "category": "mixer",
    "emoji": "☕",
    "altName": "Cold brew concentrate"
  },
  {
    "id": "mixer-cranberry-juice",
    "name": "Cranberry Juice",
    "category": "mixer",
    "emoji": "🫐",
    "altName": "Cranberry juice cocktail"
  },
  {
    "id": "mixer-espresso",
    "name": "Fresh Espresso",
    "category": "mixer",
    "emoji": "☕",
    "altName": "Freshly brewed espresso",
    "essential": true
  },
  {
    "id": "mixer-ginger-ale",
    "name": "Ginger Ale",
    "category": "mixer",
    "emoji": "🫚",
    "altName": "Ginger soda",
    "essential": true
  },
  {
    "id": "mixer-ginger-beer",
    "name": "Ginger Beer",
    "category": "mixer",
    "emoji": "🫚",
    "altName": "Spicy ginger soda",
    "essential": true
  },
  {
    "id": "mixer-grapefruit-soda",
    "name": "Grapefruit Soda",
    "category": "mixer",
    "emoji": "🕊️",
    "altName": "Squirt / Jarritos style"
  },
  {
    "id": "mixer-heavy-cream",
    "name": "Heavy Cream",
    "category": "mixer",
    "emoji": "🥛",
    "altName": "Double cream"
  },
  {
    "id": "mixer-hot-coffee",
    "name": "Hot Coffee",
    "category": "mixer",
    "emoji": "☕",
    "altName": "Fresh hot coffee"
  },
  {
    "id": "mixer-kombucha",
    "name": "Kombucha",
    "category": "mixer",
    "emoji": "🍵",
    "altName": "Fermented tea soda"
  },
  {
    "id": "mixer-lemon-lime-soda",
    "name": "Lemon-Lime Soda",
    "category": "mixer",
    "emoji": "🍋",
    "altName": "Sprite / 7-Up style"
  },
  {
    "id": "mixer-orange-juice",
    "name": "Orange Juice",
    "category": "mixer",
    "emoji": "🍊",
    "altName": "Fresh orange juice",
    "essential": true
  },
  {
    "id": "mixer-pineapple-juice",
    "name": "Pineapple Juice",
    "category": "mixer",
    "emoji": "🍍",
    "altName": "Fresh or bottled",
    "essential": true
  },
  {
    "id": "mixer-soda-water",
    "name": "Soda Water",
    "category": "mixer",
    "emoji": "🫧",
    "altName": "Club soda",
    "essential": true
  },
  {
    "id": "mixer-tomato-juice",
    "name": "Tomato Juice",
    "category": "mixer",
    "emoji": "🍅",
    "altName": "Tomato juice"
  },
  {
    "id": "mixer-tonic-water",
    "name": "Tonic Water",
    "category": "mixer",
    "emoji": "💧",
    "altName": "Indian tonic",
    "essential": true
  },
  {
    "id": "mixer-whole-milk",
    "name": "Whole Milk",
    "category": "mixer",
    "emoji": "🥛",
    "altName": "Dairy milk"
  },
  {
    "id": "mixer-yogurt",
    "name": "Yogurt",
    "category": "mixer",
    "emoji": "🥛",
    "altName": "Plain yogurt"
  },
  {
    "id": "citrus-blood-orange-juice",
    "name": "Blood Orange Juice",
    "category": "citrus-juice",
    "emoji": "🍊",
    "altName": "Fresh blood orange"
  },
  {
    "id": "citrus-grapefruit-juice",
    "name": "Grapefruit Juice",
    "category": "citrus-juice",
    "emoji": "🍊",
    "altName": "Fresh grapefruit juice",
    "essential": true
  },
  {
    "id": "citrus-lemon-juice",
    "name": "Lemon Juice",
    "category": "citrus-juice",
    "emoji": "🍋",
    "altName": "Fresh lemon juice",
    "essential": true
  },
  {
    "id": "citrus-lime-juice",
    "name": "Lime Juice",
    "category": "citrus-juice",
    "emoji": "🟢",
    "altName": "Fresh lime juice",
    "essential": true
  },
  {
    "id": "citrus-lime-wedges",
    "name": "Lime Wedges",
    "category": "citrus-juice",
    "emoji": "🟢",
    "altName": "Cut lime wedges"
  },
  {
    "id": "citrus-orange-slices",
    "name": "Orange Slices",
    "category": "citrus-juice",
    "emoji": "🍊",
    "altName": "Fresh orange slices"
  },
  {
    "id": "citrus-yuzu-juice",
    "name": "Yuzu Juice",
    "category": "citrus-juice",
    "emoji": "🍋",
    "altName": "Yuzu citrus juice"
  },
  {
    "id": "sweet-agave-syrup",
    "name": "Agave Syrup",
    "category": "sweetener-syrup",
    "emoji": "🌵",
    "altName": "Agave nectar",
    "essential": true
  },
  {
    "id": "sweet-cinnamon-syrup",
    "name": "Cinnamon Syrup",
    "category": "sweetener-syrup",
    "emoji": "🟤",
    "altName": "Cinnamon syrup"
  },
  {
    "id": "sweet-demerara-syrup",
    "name": "Demerara Syrup",
    "category": "sweetener-syrup",
    "emoji": "🟤",
    "altName": "Rich sugar syrup"
  },
  {
    "id": "sweet-falernum",
    "name": "Falernum",
    "category": "sweetener-syrup",
    "emoji": "🌴",
    "altName": "Spiced lime-almond syrup"
  },
  {
    "id": "sweet-grenadine",
    "name": "Grenadine",
    "category": "sweetener-syrup",
    "emoji": "🔴",
    "altName": "Pomegranate syrup",
    "essential": true
  },
  {
    "id": "sweet-honey-ginger-syrup",
    "name": "Honey-Ginger Syrup",
    "category": "sweetener-syrup",
    "emoji": "🍯",
    "altName": "Honey syrup with ginger"
  },
  {
    "id": "sweet-honey-syrup",
    "name": "Honey Syrup",
    "category": "sweetener-syrup",
    "emoji": "🍯",
    "altName": "Honey diluted with water",
    "essential": true
  },
  {
    "id": "sweet-maple-syrup",
    "name": "Maple Syrup",
    "category": "sweetener-syrup",
    "emoji": "🍁",
    "altName": "Pure maple syrup"
  },
  {
    "id": "sweet-orgeat",
    "name": "Orgeat",
    "category": "sweetener-syrup",
    "emoji": "🌰",
    "altName": "Almond syrup"
  },
  {
    "id": "sweet-passionfruit-syrup",
    "name": "Passion Fruit Syrup",
    "category": "sweetener-syrup",
    "emoji": "🟡",
    "altName": "Passion fruit syrup"
  },
  {
    "id": "sweet-raspberry-syrup",
    "name": "Raspberry Syrup",
    "category": "sweetener-syrup",
    "emoji": "🩷",
    "altName": "Raspberry syrup"
  },
  {
    "id": "sweet-rosemary-syrup",
    "name": "Rosemary Syrup",
    "category": "sweetener-syrup",
    "emoji": "🌿",
    "altName": "Rosemary syrup"
  },
  {
    "id": "sweet-simple-syrup",
    "name": "Simple Syrup",
    "category": "sweetener-syrup",
    "emoji": "🍯",
    "altName": "1:1 sugar syrup",
    "essential": true
  },
  {
    "id": "sweet-vanilla-syrup",
    "name": "Vanilla Syrup",
    "category": "sweetener-syrup",
    "emoji": "🌼",
    "altName": "Vanilla syrup"
  },
  {
    "id": "syrup-basil",
    "name": "Basil Syrup",
    "category": "sweetener-syrup",
    "emoji": "🌿",
    "altName": "Fresh basil syrup"
  },
  {
    "id": "syrup-blackberry",
    "name": "Blackberry Syrup",
    "category": "sweetener-syrup",
    "emoji": "🫐",
    "altName": "Blackberry syrup"
  },
  {
    "id": "syrup-blueberry",
    "name": "Blueberry Syrup",
    "category": "sweetener-syrup",
    "emoji": "🫐",
    "altName": "Blueberry syrup"
  },
  {
    "id": "syrup-cardamom",
    "name": "Cardamom Syrup",
    "category": "sweetener-syrup",
    "emoji": "🌱",
    "altName": "Green cardamom syrup"
  },
  {
    "id": "syrup-chili",
    "name": "Chili Syrup",
    "category": "sweetener-syrup",
    "emoji": "🌶️",
    "altName": "Chili-infused syrup"
  },
  {
    "id": "syrup-coffee",
    "name": "Coffee Syrup",
    "category": "sweetener-syrup",
    "emoji": "☕",
    "altName": "Coffee syrup"
  },
  {
    "id": "syrup-fig",
    "name": "Fig Syrup",
    "category": "sweetener-syrup",
    "emoji": "🟣",
    "altName": "Fig syrup"
  },
  {
    "id": "syrup-ginger",
    "name": "Ginger Syrup",
    "category": "sweetener-syrup",
    "emoji": "🫚",
    "altName": "Fresh ginger syrup"
  },
  {
    "id": "syrup-hibiscus",
    "name": "Hibiscus Syrup",
    "category": "sweetener-syrup",
    "emoji": "🌺",
    "altName": "Hibiscus syrup"
  },
  {
    "id": "syrup-lavender",
    "name": "Lavender Syrup",
    "category": "sweetener-syrup",
    "emoji": "💜",
    "altName": "Lavender syrup"
  },
  {
    "id": "syrup-lemongrass",
    "name": "Lemongrass Syrup",
    "category": "sweetener-syrup",
    "emoji": "🌾",
    "altName": "Lemongrass syrup"
  },
  {
    "id": "syrup-mango",
    "name": "Mango Syrup",
    "category": "sweetener-syrup",
    "emoji": "🥭",
    "altName": "Mango syrup"
  },
  {
    "id": "syrup-mint",
    "name": "Mint Syrup",
    "category": "sweetener-syrup",
    "emoji": "🌿",
    "altName": "Fresh mint syrup"
  },
  {
    "id": "syrup-pandan",
    "name": "Pandan Syrup",
    "category": "sweetener-syrup",
    "emoji": "🌿",
    "altName": "Pandan leaf syrup"
  },
  {
    "id": "syrup-peach",
    "name": "Peach Syrup",
    "category": "sweetener-syrup",
    "emoji": "🍑",
    "altName": "Peach syrup"
  },
  {
    "id": "syrup-pomegranate",
    "name": "Pomegranate Syrup",
    "category": "sweetener-syrup",
    "emoji": "🔴",
    "altName": "Pomegranate syrup"
  },
  {
    "id": "syrup-raspberry",
    "name": "Raspberry Syrup",
    "category": "sweetener-syrup",
    "emoji": "🍓",
    "altName": "Raspberry syrup"
  },
  {
    "id": "syrup-salted-caramel",
    "name": "Salted Caramel Syrup",
    "category": "sweetener-syrup",
    "emoji": "🧂",
    "altName": "Caramel syrup with salt"
  },
  {
    "id": "syrup-tamarind",
    "name": "Tamarind Syrup",
    "category": "sweetener-syrup",
    "emoji": "🟤",
    "altName": "Tamarind syrup"
  },
  {
    "id": "syrup-watermelon",
    "name": "Watermelon Syrup",
    "category": "sweetener-syrup",
    "emoji": "🍉",
    "altName": "Watermelon syrup"
  },
  {
    "id": "bitter-angostura",
    "name": "Angostura Bitters",
    "category": "bitter",
    "emoji": "🌶️",
    "altName": "Aromatic bitters",
    "essential": true
  },
  {
    "id": "bitter-cucumber",
    "name": "Cucumber Bitters",
    "category": "bitter",
    "emoji": "🥒",
    "altName": "Non-alcoholic if required"
  },
  {
    "id": "bitter-orange",
    "name": "Orange Bitters",
    "category": "bitter",
    "emoji": "🍊",
    "altName": "Orange bitters"
  },
  {
    "id": "bitter-peychauds",
    "name": "Peychaud's Bitters",
    "category": "bitter",
    "emoji": "❤️",
    "altName": "New Orleans bitters"
  },
  {
    "id": "additive-aquafaba",
    "name": "Aquafaba",
    "category": "additive",
    "emoji": "🫘",
    "altName": "Chickpea brine"
  },
  {
    "id": "additive-egg-white",
    "name": "Egg White",
    "category": "additive",
    "emoji": "🥚",
    "altName": "Fresh egg white",
    "essential": true
  },
  {
    "id": "solution-saline",
    "name": "Saline Solution",
    "category": "additive",
    "emoji": "🧂",
    "altName": "10-20% salt solution"
  },
  {
    "id": "fruit-blueberry",
    "name": "Blueberries",
    "category": "fruit-produce",
    "emoji": "🫐",
    "altName": "Fresh blueberries"
  },
  {
    "id": "fruit-dragonfruit-puree",
    "name": "Dragon Fruit Purée",
    "category": "fruit-produce",
    "emoji": "🐉",
    "altName": "Dragon fruit purée"
  },
  {
    "id": "fruit-grapes",
    "name": "Green Grapes",
    "category": "fruit-produce",
    "emoji": "🍇",
    "altName": "Fresh grapes"
  },
  {
    "id": "fruit-guava-juice",
    "name": "Guava Juice",
    "category": "fruit-produce",
    "emoji": "🟠",
    "altName": "Guava nectar"
  },
  {
    "id": "fruit-kiwi",
    "name": "Kiwi",
    "category": "fruit-produce",
    "emoji": "🥝",
    "altName": "Fresh kiwi"
  },
  {
    "id": "fruit-lychee-syrup",
    "name": "Lychee Syrup",
    "category": "fruit-produce",
    "emoji": "🌸",
    "altName": "Lychee syrup"
  },
  {
    "id": "fruit-mango-puree",
    "name": "Mango Purée",
    "category": "fruit-produce",
    "emoji": "🥭",
    "altName": "Mango pulp"
  },
  {
    "id": "fruit-passionfruit-puree",
    "name": "Passion Fruit Purée",
    "category": "fruit-produce",
    "emoji": "🟡",
    "altName": "Passion fruit pulp"
  },
  {
    "id": "fruit-peach-puree",
    "name": "Peach Purée",
    "category": "fruit-produce",
    "emoji": "🍑",
    "altName": "White peach purée"
  },
  {
    "id": "fruit-pear-nectar",
    "name": "Pear Nectar",
    "category": "fruit-produce",
    "emoji": "🍐",
    "altName": "Pear juice / nectar"
  },
  {
    "id": "fruit-plum-puree",
    "name": "Plum Purée",
    "category": "fruit-produce",
    "emoji": "🟣",
    "altName": "Plum purée"
  },
  {
    "id": "fruit-pomegranate-juice",
    "name": "Pomegranate Juice",
    "category": "fruit-produce",
    "emoji": "🔴",
    "altName": "Pomegranate juice"
  },
  {
    "id": "fruit-strawberry",
    "name": "Strawberry",
    "category": "fruit-produce",
    "emoji": "🍓",
    "altName": "Fresh strawberry"
  },
  {
    "id": "fruit-watermelon-juice",
    "name": "Watermelon Juice",
    "category": "fruit-produce",
    "emoji": "🍉",
    "altName": "Fresh watermelon juice"
  },
  {
    "id": "garnish-apple-fan",
    "name": "Apple Fan",
    "category": "garnish",
    "emoji": "🍎",
    "altName": "Apple slices"
  },
  {
    "id": "garnish-basil",
    "name": "Basil",
    "category": "garnish",
    "emoji": "🌱",
    "altName": "Fresh basil"
  },
  {
    "id": "garnish-berries",
    "name": "Mixed Berries",
    "category": "garnish",
    "emoji": "🫐",
    "altName": "Fresh berries"
  },
  {
    "id": "garnish-blackberry",
    "name": "Blackberries",
    "category": "garnish",
    "emoji": "🫐",
    "altName": "Fresh blackberries"
  },
  {
    "id": "garnish-candied-ginger",
    "name": "Candied Ginger",
    "category": "garnish",
    "emoji": "🫚",
    "altName": "Candied ginger"
  },
  {
    "id": "garnish-celery-stalk",
    "name": "Celery Stalk",
    "category": "garnish",
    "emoji": "🥬",
    "altName": "Celery garnish"
  },
  {
    "id": "garnish-chili-salt",
    "name": "Chili Salt",
    "category": "garnish",
    "emoji": "🌶️",
    "altName": "Chili salt rim"
  },
  {
    "id": "garnish-cinnamon-sugar",
    "name": "Cinnamon Sugar",
    "category": "garnish",
    "emoji": "🟤",
    "altName": "Cinnamon sugar rim"
  },
  {
    "id": "garnish-cocktail-cherry",
    "name": "Cocktail Cherry",
    "category": "garnish",
    "emoji": "🍒",
    "altName": "Maraschino cherry",
    "essential": true
  },
  {
    "id": "garnish-cocktail-onion",
    "name": "Cocktail Onion",
    "category": "garnish",
    "emoji": "🧅",
    "altName": "Pickled cocktail onion"
  },
  {
    "id": "garnish-coconut-flakes",
    "name": "Coconut Flakes",
    "category": "garnish",
    "emoji": "🥥",
    "altName": "Toasted coconut flakes"
  },
  {
    "id": "garnish-coffee-beans",
    "name": "Coffee Beans",
    "category": "garnish",
    "emoji": "☕",
    "altName": "Roasted coffee beans"
  },
  {
    "id": "garnish-cucumber",
    "name": "Cucumber",
    "category": "garnish",
    "emoji": "🥒",
    "altName": "Fresh cucumber"
  },
  {
    "id": "garnish-edible-flower",
    "name": "Edible Flower",
    "category": "garnish",
    "emoji": "🌸",
    "altName": "Food-safe flower"
  },
  {
    "id": "garnish-grapefruit-twist",
    "name": "Grapefruit Twist",
    "category": "garnish",
    "emoji": "🍊",
    "altName": "Grapefruit peel twist"
  },
  {
    "id": "garnish-grapefruit-wedge",
    "name": "Grapefruit Wedge",
    "category": "garnish",
    "emoji": "🍊",
    "altName": "Fresh grapefruit wedge"
  },
  {
    "id": "garnish-grapes",
    "name": "Grapes",
    "category": "garnish",
    "emoji": "🍇",
    "altName": "Fresh grape garnish"
  },
  {
    "id": "garnish-grated-chocolate",
    "name": "Grated Chocolate",
    "category": "garnish",
    "emoji": "🍫",
    "altName": "Chocolate garnish"
  },
  {
    "id": "garnish-lemon-twist",
    "name": "Lemon Twist",
    "category": "garnish",
    "emoji": "🍋",
    "altName": "Lemon peel twist",
    "essential": true
  },
  {
    "id": "garnish-lemon-wheel",
    "name": "Lemon Wheel",
    "category": "garnish",
    "emoji": "🍋",
    "altName": "Fresh lemon wheel"
  },
  {
    "id": "garnish-lime-wedge",
    "name": "Lime Wedge",
    "category": "garnish",
    "emoji": "🟢",
    "altName": "Fresh lime wedge"
  },
  {
    "id": "garnish-lime-wheel",
    "name": "Lime Wheel",
    "category": "garnish",
    "emoji": "🟢",
    "altName": "Fresh lime wheel",
    "essential": true
  },
  {
    "id": "garnish-mint",
    "name": "Mint",
    "category": "garnish",
    "emoji": "🌿",
    "altName": "Fresh mint",
    "essential": true
  },
  {
    "id": "garnish-nutmeg",
    "name": "Nutmeg",
    "category": "garnish",
    "emoji": "🌰",
    "altName": "Fresh grated nutmeg"
  },
  {
    "id": "garnish-olive",
    "name": "Green Olive",
    "category": "garnish",
    "emoji": "🫒",
    "altName": "Cocktail olive"
  },
  {
    "id": "garnish-orange-slice",
    "name": "Orange Slice",
    "category": "garnish",
    "emoji": "🍊",
    "altName": "Fresh orange slice",
    "essential": true
  },
  {
    "id": "garnish-orange-twist",
    "name": "Orange Twist",
    "category": "garnish",
    "emoji": "🍊",
    "altName": "Orange peel twist",
    "essential": true
  },
  {
    "id": "garnish-passionfruit-half",
    "name": "Passion Fruit Half",
    "category": "garnish",
    "emoji": "🟡",
    "altName": "Half passion fruit"
  },
  {
    "id": "garnish-peach-slice",
    "name": "Peach Slice",
    "category": "garnish",
    "emoji": "🍑",
    "altName": "Fresh peach slice"
  },
  {
    "id": "garnish-pear-slice",
    "name": "Pear Slice",
    "category": "garnish",
    "emoji": "🍐",
    "altName": "Fresh pear slice"
  },
  {
    "id": "garnish-pineapple-wedge",
    "name": "Pineapple Wedge",
    "category": "garnish",
    "emoji": "🍍",
    "altName": "Pineapple wedge",
    "essential": true
  },
  {
    "id": "garnish-raspberry",
    "name": "Raspberries",
    "category": "garnish",
    "emoji": "🩷",
    "altName": "Fresh raspberries"
  },
  {
    "id": "garnish-rosemary",
    "name": "Rosemary",
    "category": "garnish",
    "emoji": "🌿",
    "altName": "Fresh rosemary"
  },
  {
    "id": "garnish-sage",
    "name": "Sage",
    "category": "garnish",
    "emoji": "🌿",
    "altName": "Fresh sage"
  },
  {
    "id": "garnish-salt",
    "name": "Salt",
    "category": "garnish",
    "emoji": "🧂",
    "altName": "Kosher / sea salt"
  },
  {
    "id": "garnish-shiso",
    "name": "Shiso Leaf",
    "category": "garnish",
    "emoji": "🌿",
    "altName": "Shiso leaf"
  },
  {
    "id": "garnish-strawberry",
    "name": "Strawberry Garnish",
    "category": "garnish",
    "emoji": "🍓",
    "altName": "Fresh strawberry"
  },
  {
    "id": "garnish-sugar",
    "name": "Sugar",
    "category": "garnish",
    "emoji": "⬜",
    "altName": "Granulated sugar"
  },
  {
    "id": "garnish-thai-basil",
    "name": "Thai Basil",
    "category": "garnish",
    "emoji": "🌿",
    "altName": "Fresh Thai basil"
  },
  {
    "id": "garnish-thyme",
    "name": "Thyme",
    "category": "garnish",
    "emoji": "🌿",
    "altName": "Fresh thyme"
  },
  {
    "id": "brine-olive",
    "name": "Olive Brine",
    "category": "savory",
    "emoji": "🫒",
    "altName": "Olive brine"
  },
  {
    "id": "sauce-hot",
    "name": "Hot Sauce",
    "category": "savory",
    "emoji": "🌶️",
    "altName": "Pepper sauce"
  },
  {
    "id": "sauce-worcestershire",
    "name": "Worcestershire Sauce",
    "category": "savory",
    "emoji": "🧂",
    "altName": "Savory sauce"
  },
  {
    "id": "seasoning-black-pepper",
    "name": "Black Pepper",
    "category": "savory",
    "emoji": "⚫",
    "altName": "Freshly ground pepper"
  },
  {
    "id": "seasoning-celery-salt",
    "name": "Celery Salt",
    "category": "savory",
    "emoji": "🧂",
    "altName": "Celery salt"
  },
  {
    "id": "tea-earl-grey",
    "name": "Earl Grey Tea",
    "category": "tea-infusion",
    "emoji": "🫖",
    "altName": "Strong chilled tea"
  },
  {
    "id": "tea-green",
    "name": "Green Tea",
    "category": "tea-infusion",
    "emoji": "🍵",
    "altName": "Chilled green tea"
  },
  {
    "id": "tea-hibiscus",
    "name": "Hibiscus Tea",
    "category": "tea-infusion",
    "emoji": "🌺",
    "altName": "Strong chilled tea"
  },
  {
    "id": "tea-jasmine",
    "name": "Jasmine Tea",
    "category": "tea-infusion",
    "emoji": "🍵",
    "altName": "Brewed jasmine tea"
  },
  {
    "id": "tea-matcha",
    "name": "Matcha Tea",
    "category": "tea-infusion",
    "emoji": "🍵",
    "altName": "Whisked matcha"
  },
  {
    "id": "water-orange-blossom-water",
    "name": "Orange Blossom Water",
    "category": "flavor-water",
    "emoji": "🌼",
    "altName": "Orange blossom water"
  },
  {
    "id": "water-rose-water",
    "name": "Rose Water",
    "category": "flavor-water",
    "emoji": "🌹",
    "altName": "Culinary rose water"
  },
  {
    "id": "zero-nonalcoholic-amaro",
    "name": "Non-Alcoholic Amaro",
    "category": "zero-proof-spirit",
    "emoji": "🟥",
    "altName": "Zero-proof bitter aperitif"
  },
  {
    "id": "zero-nonalcoholic-aperitif",
    "name": "Non-Alcoholic Aperitif",
    "category": "zero-proof-spirit",
    "emoji": "🚫",
    "altName": "Bitter aperitif alternative"
  },
  {
    "id": "zero-nonalcoholic-gin",
    "name": "Non-Alcoholic Gin",
    "category": "zero-proof-spirit",
    "emoji": "🚫",
    "altName": "Gin alternative"
  },
  {
    "id": "zero-nonalcoholic-rum",
    "name": "Non-Alcoholic Rum",
    "category": "zero-proof-spirit",
    "emoji": "🚫",
    "altName": "Zero-proof rum alternative"
  },
  {
    "id": "zero-nonalcoholic-tequila",
    "name": "Non-Alcoholic Tequila",
    "category": "zero-proof-spirit",
    "emoji": "🚫",
    "altName": "Zero-proof tequila alternative"
  },
  {
    "id": "zero-nonalcoholic-whiskey",
    "name": "Non-Alcoholic Whiskey",
    "category": "zero-proof-spirit",
    "emoji": "🚫",
    "altName": "Zero-proof whiskey alternative"
  },
  {
    "id": "smoke-wood-chips",
    "name": "Wood Smoke",
    "category": "bar-tool",
    "emoji": "💨",
    "altName": "Smoking chips / smoke aroma"
  }
];

export const BAR_INGREDIENT_INDEX: Record<string, BarIngredient> =
  Object.fromEntries(BAR_INGREDIENTS.map((i) => [i.id, i]));

export const BAR_CATEGORY_LABEL: Record<BarIngredientCategory, string> = {
  "spirits": "Spirits",
  "liqueur-vermouth": "Liqueurs & Vermouth",
  "amaro-bitters": "Amaro & Bitters",
  "wine-sparkling": "Wine & Sparkling",
  "mixer": "Mixers",
  "citrus-juice": "Citrus & Juices",
  "sweetener-syrup": "Sweeteners & Syrups",
  "bitter": "Bitters",
  "additive": "Additives",
  "fruit-produce": "Fruit & Produce",
  "garnish": "Garnishes",
  "savory": "Savory Add-ins",
  "tea-infusion": "Tea & Infusions",
  "flavor-water": "Flavor Waters",
  "zero-proof-spirit": "Zero-Proof Spirits",
  "bar-tool": "Bar Tools / Effects"
};

export const BAR_CATEGORY_ORDER: BarIngredientCategory[] = [
  "spirits",
  "liqueur-vermouth",
  "amaro-bitters",
  "wine-sparkling",
  "mixer",
  "citrus-juice",
  "sweetener-syrup",
  "bitter",
  "additive",
  "fruit-produce",
  "garnish",
  "savory",
  "tea-infusion",
  "flavor-water",
  "zero-proof-spirit",
  "bar-tool"
];
