// AUTO-GENERATED by scripts/import-cocktaildb.ts
// Do not edit by hand — re-run the import to refresh.
import type { Cocktail } from "@/types/bar";

export const COCKTAILDB_RECIPES: Cocktail[] = [
  {
    "id": "cdb-110-in-the-shade",
    "name": "110 in the shade",
    "description": "Bira ile hafif ve ferah bir içecek, keyifli bir atıştırmalık.",
    "emoji": "🌵",
    "technique": "build",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-tequila",
        "amount": "1.5 oz"
      }
    ],
    "steps": [
      "1. Shooter'ı bardağa bırakın.",
      "2. Bira ile doldurun."
    ],
    "tags": [
      "beer",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:110-in-the-shade"
  },
  {
    "id": "cdb-151-florida-bushwacker",
    "name": "151 Florida Bushwacker",
    "description": "Tatlı ve yoğun bir içecek, çikolata ile zenginleştirilmiş.",
    "emoji": "🍹",
    "technique": "blend",
    "glass": "rocks",
    "difficulty": "orta",
    "prepTimeMinutes": 6,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-coconut",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "spirit-rum-white",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "spirit-rum-dark",
        "amount": "1/2 oz Bacardi"
      },
      {
        "ingredientId": "liqueur-creme-de-cacao",
        "amount": "1 oz"
      },
      {
        "ingredientId": "liqueur-triple-sec",
        "amount": "1 oz"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri birleştirin.",
      "2. Pürüzsüz olana kadar karıştırın.",
      "3. İsteğe bağlı olarak çikolata rendesi ile süsleyin."
    ],
    "tags": [
      "shake",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:151-florida-bushwacker"
  },
  {
    "id": "cdb-155-belmont",
    "name": "155 Belmont",
    "description": "Ferahlık veren bir içecek, havuç ile sunumu zenginleştirir.",
    "emoji": "🍹",
    "technique": "blend",
    "glass": "wine",
    "difficulty": "orta",
    "prepTimeMinutes": 5,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-rum-dark",
        "amount": "1 shot"
      },
      {
        "ingredientId": "spirit-rum-white",
        "amount": "2 shots"
      },
      {
        "ingredientId": "spirit-vodka",
        "amount": "1 shot"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "1 shot"
      }
    ],
    "steps": [
      "1. Buz ile karıştırın.",
      "2. Şarap kadehinde servis edin.",
      "3. Havuç ile süsleyin."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:155-belmont"
  },
  {
    "id": "cdb-252",
    "name": "252",
    "description": "Hızlı ve etkili bir shot, acı bir deneyim sunar.",
    "emoji": "🥃",
    "technique": "build",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-rum-dark",
        "amount": "1/2 shot Bacardi"
      },
      {
        "ingredientId": "spirit-bourbon",
        "amount": "1/2 shot"
      }
    ],
    "steps": [
      "1. İki malzemeyi shot bardağına ekleyin, içip hızlıca sarhoş olun."
    ],
    "tags": [
      "shot",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:252"
  },
  {
    "id": "cdb-3-wise-men",
    "name": "3 Wise Men",
    "description": "Yoğun bir içim deneyimi, hızlı bir etki yaratır.",
    "emoji": "🥃",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-bourbon",
        "amount": "1/3 oz"
      }
    ],
    "steps": [
      "1. Malzemeleri bir bardağa koyun.",
      "2. Hızla için."
    ],
    "tags": [
      "shot",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:3-wise-men"
  },
  {
    "id": "cdb-3-mile-long-island-iced-tea",
    "name": "3-Mile Long Island Iced Tea",
    "description": "Tatlı ve ferahlatıcı, klasik bir karışım.",
    "emoji": "🌵",
    "technique": "build",
    "glass": "highball",
    "difficulty": "zor",
    "prepTimeMinutes": 6,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-gin",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "spirit-rum-white",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "spirit-tequila",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "liqueur-triple-sec",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "spirit-vodka",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "mixer-cola",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "bitter-angostura",
        "amount": "1 wedge",
        "optional": true
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "Garnish with"
      }
    ],
    "steps": [
      "1. 14 oz bardağı buz ve alkol ile doldurun.",
      "2. Bardağın 2/3'ünü kola ile doldurun, kalanını tatlı ve ekşi ile tamamlayın.",
      "3. Bir tutam acı ve limon dilimi ile süsleyin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:3-mile-long-island-iced-tea"
  },
  {
    "id": "cdb-410-gone",
    "name": "410 Gone",
    "description": "Hızlı ve eğlenceli bir karışım, keyifli bir içim sunar.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-vodka",
        "amount": "2-3 oz"
      },
      {
        "ingredientId": "mixer-cola",
        "amount": "tatlandırıcı"
      }
    ],
    "steps": [
      "1. Malzemeleri karıştırın ve tadını çıkarın!"
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:410-gone"
  },
  {
    "id": "cdb-50-50",
    "name": "50/50",
    "description": "Tatlı ve yoğun bir içecek, narenciye ile ferahlatır.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-vodka",
        "amount": "2 1/2 oz"
      },
      {
        "ingredientId": "liqueur-triple-sec",
        "amount": "1 splash"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "Fill with"
      }
    ],
    "steps": [
      "1. Bardağı ezilmiş buz ile doldurun.",
      "2. Vodka ekleyin.",
      "3. Bir miktar Grand Marnier ekleyin.",
      "4. Portakal suyu ile doldurun."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:50-50"
  },
  {
    "id": "cdb-501-blue",
    "name": "501 Blue",
    "description": "501 Blue, ferah ve hafif tatlı bir içecek, buzla karıştırılır.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-triple-sec",
        "amount": "tatlandırıcı"
      },
      {
        "ingredientId": "spirit-vodka",
        "amount": "tatlandırıcı"
      },
      {
        "ingredientId": "mixer-lemon-lime-soda",
        "amount": "tatlandırıcı"
      }
    ],
    "steps": [
      "1. Buzlu bir bardağa eşit miktarda karıştırın."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:501-blue"
  },
  {
    "id": "cdb-57-chevy-with-a-white-license-plate",
    "name": "57 Chevy with a White License Plate",
    "description": "57 Chevy, tatlı ve kremsi bir kokteyl, karıştırılarak servis edilir.",
    "emoji": "🍹",
    "technique": "stir",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-creme-de-cacao",
        "amount": "1 oz white"
      },
      {
        "ingredientId": "spirit-vodka",
        "amount": "1 oz"
      }
    ],
    "steps": [
      "1. Buz dolu bir rocks bardağına beyaz krema de kacao ve votka ekleyin.",
      "2. Karıştırın."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:57-chevy-with-a-white-license-plate"
  },
  {
    "id": "cdb-69-special",
    "name": "69 Special",
    "description": "69 Special, ferahlatıcı ve hafif ekşi bir içecek, limon suyu ile tatlandırılır.",
    "emoji": "🌿",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-gin",
        "amount": "2 oz dry"
      },
      {
        "ingredientId": "mixer-lemon-lime-soda",
        "amount": "4 oz"
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "0.75 oz"
      }
    ],
    "steps": [
      "1. 2 oz. cin dökün.",
      "2. 4 oz. 7-up ekleyin.",
      "3. Tat vermesi için limon suyu ekleyin.",
      "4. Zayıfsanız, bardağı daha fazla 7-Up ile doldurun."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:69-special"
  },
  {
    "id": "cdb-747",
    "name": "747",
    "description": "747, yoğun ve tatlı bir içecek, katmanlı değil karıştırılarak servis edilir.",
    "emoji": "☕",
    "technique": "build",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-coffee",
        "amount": "1/3 part"
      },
      {
        "ingredientId": "liqueur-baileys",
        "amount": "1/3 part"
      }
    ],
    "steps": [
      "1. Kahlua, ardından Baileys ve Frangelico'yu dökün, soğutmayın ve katman yapmayın."
    ],
    "tags": [
      "shot",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:747"
  },
  {
    "id": "cdb-747-drink",
    "name": "747 Drink",
    "description": "747 Drink, ferah ve meyvemsi bir içecek, Sprite ile tamamlanır.",
    "emoji": "💗",
    "technique": "build",
    "glass": "highball",
    "difficulty": "orta",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-vodka",
        "amount": "1 oz"
      },
      {
        "ingredientId": "citrus-lime",
        "amount": "1 oz"
      },
      {
        "ingredientId": "mixer-cranberry",
        "amount": "1 oz"
      },
      {
        "ingredientId": "mixer-lemon-lime-soda",
        "amount": "Top"
      }
    ],
    "steps": [
      "1. Buz dolu bir Collins bardağına doldurun.",
      "2. Votka, lime likörü ve kızılcık suyu dökün.",
      "3. Sprite ile doldurun.",
      "4. Lime dilimi veya kızılcık ile süsleyin."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:747-drink"
  },
  {
    "id": "cdb-9-1-2-weeks",
    "name": "9 1/2 Weeks",
    "description": "9 1/2 Weeks, tatlı ve meyvemsi bir kokteyl, çilek ile süslenir.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-vodka",
        "amount": "2 oz"
      },
      {
        "ingredientId": "liqueur-triple-sec",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "1 oz"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri bir karıştırıcıda birleştirin.",
      "2. Soğutun ve kokteyl bardağına süzün.",
      "3. Dilimlenmiş çilek ile süsleyin."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:9-1-2-weeks"
  },
  {
    "id": "cdb-a-day-at-the-beach",
    "name": "A Day at the Beach",
    "description": "A Day at the Beach, tropikal ve tatlı bir içecek, ananas ve çilek ile süslenir.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "highball",
    "difficulty": "orta",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-coconut",
        "amount": "1 oz"
      },
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "4 oz"
      },
      {
        "ingredientId": "sweet-grenadine",
        "amount": "1/2 oz"
      }
    ],
    "steps": [
      "1. Rom, Amaretto ve portakal suyunu buz dolu bir shaker'da çalkalayın.",
      "2. Buz üzerine süzerek yüksek bir bardağa dökün.",
      "3. Grenadin ekleyin ve ananas dilimi ile çilek ile süsleyin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:a-day-at-the-beach"
  },
  {
    "id": "cdb-a-furlong-too-late",
    "name": "A Furlong Too Late",
    "description": "A Furlong Too Late, baharatlı ve ferah bir içecek, limon twist ile süslenir.",
    "emoji": "🍹",
    "technique": "stir",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-rum-white",
        "amount": "2 oz"
      },
      {
        "ingredientId": "mixer-ginger-beer",
        "amount": "4 oz"
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "1 twist of"
      }
    ],
    "steps": [
      "1. Rom ve zencefilli birayı neredeyse buz dolu bir yüksek bardağa dökün.",
      "2. İyi karıştırın.",
      "3. Limon twist ile süsleyin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:a-furlong-too-late"
  },
  {
    "id": "cdb-a-gilligan-s-island",
    "name": "A Gilligan's Island",
    "description": "Ferah ve hafif bir içecek, yaz akşamları için ideal.",
    "emoji": "💗",
    "technique": "shake",
    "glass": "highball",
    "difficulty": "orta",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-vodka",
        "amount": "1 oz"
      },
      {
        "ingredientId": "liqueur-peach",
        "amount": "1 oz"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "3 oz"
      },
      {
        "ingredientId": "mixer-cranberry",
        "amount": "3 oz"
      }
    ],
    "steps": [
      "1. Shaken, not stirred!"
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:a-gilligan-s-island"
  },
  {
    "id": "cdb-a-night-in-old-mandalay",
    "name": "A Night In Old Mandalay",
    "description": "Tatlı ve meyvemsi bir tat profili, tropikal bir deneyim sunar.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "highball",
    "difficulty": "orta",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-rum-white",
        "amount": "1 oz"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "1 oz"
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "mixer-ginger-beer",
        "amount": "3 oz"
      }
    ],
    "steps": [
      "1. Buz dolu bir shaker'a hafif rom, añejo rom, portakal suyu ve limon suyu ekleyin.",
      "2. İyice çalkalayın.",
      "3. Buz dolu bir highball bardağa süzün.",
      "4. Zencefilli gazoz ile tamamlayın.",
      "5. Limon kabuğu ile süsleyin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:a-night-in-old-mandalay"
  },
  {
    "id": "cdb-a-piece-of-ass",
    "name": "A Piece of Ass",
    "description": "Tatlı ve ekşi bir karışım, hızlı bir içim için ideal.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "1 shot"
      }
    ],
    "steps": [
      "1. Bardağa buz koyun.",
      "2. Shotları dökün.",
      "3. Ekşi karışım ile doldurun."
    ],
    "tags": [
      "other / unknown",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:a-piece-of-ass"
  },
  {
    "id": "cdb-a-splash-of-nash",
    "name": "A Splash of Nash",
    "description": "Tatlı ve ferah bir içecek, eğlenceli bir shot deneyimi sunar.",
    "emoji": "💗",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "mixer-cranberry",
        "amount": "2 oz"
      },
      {
        "ingredientId": "mixer-soda",
        "amount": "2 oz"
      },
      {
        "ingredientId": "liqueur-melon",
        "amount": "0.5 oz"
      }
    ],
    "steps": [
      "1. Muz ve kavun likörlerini içeren shot bardağını soda suyu ve kızılcık suyu dolu 9 oz'luk bir highball bardağa bırakın.",
      "2. Tek seferde içebilirsiniz."
    ],
    "tags": [
      "shot",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:a-splash-of-nash"
  },
  {
    "id": "cdb-a-true-amaretto-sour",
    "name": "A True Amaretto Sour",
    "description": "Tatlı ve ekşi dengesiyle yoğun bir lezzet sunar.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "1 jigger"
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "Juice of 1/2"
      },
      {
        "ingredientId": "garnish-cherry",
        "amount": "tatlandırıcı",
        "optional": true
      }
    ],
    "steps": [
      "1. Eski moda bir bardağın kenarını limonla ovalayın ve toz şekerle kaplayın.",
      "2. 1 ölçü Amaretto'yu yarım limon suyu ile çalkalayın.",
      "3. Bardağa süzün ve buz ekleyin.",
      "4. Maraschino kirazı ile süsleyin."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:a-true-amaretto-sour"
  },
  {
    "id": "cdb-a-j",
    "name": "A. J.",
    "description": "Hafif ve ferahlatıcı bir kokteyl, klasik bir seçim.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "citrus-grapefruit",
        "amount": "1 oz"
      }
    ],
    "steps": [
      "1. Malzemeleri buz ile çalkalayın, kokteyl bardağına süzün ve servis edin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:a-j"
  },
  {
    "id": "cdb-a-d-m-after-dinner-mint",
    "name": "A.D.M. (After Dinner Mint)",
    "description": "Ferahlık veren bir içecek, akşam yemeklerinden sonra ideal.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-creme-de-cacao",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "spirit-vodka",
        "amount": "1/2 oz"
      }
    ],
    "steps": [
      "1. Şiddetle çalkalayın."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:a-d-m-after-dinner-mint"
  },
  {
    "id": "cdb-a1",
    "name": "A1",
    "description": "Tatlı ve yoğun bir karışım, serinletici bir içecek deneyimi sunar.",
    "emoji": "🌿",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "orta",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-gin",
        "amount": "1 3/4 shot"
      },
      {
        "ingredientId": "liqueur-triple-sec",
        "amount": "1 Shot"
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "1/4 Shot"
      },
      {
        "ingredientId": "sweet-grenadine",
        "amount": "1/8 Shot"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri bir kokteyl shaker'ına dökün, karıştırın ve soğutulmuş bir bardağa buz ile servis edin."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:a1"
  },
  {
    "id": "cdb-abbey-cocktail",
    "name": "Abbey Cocktail",
    "description": "Tatlı ve meyvemsi bir kokteyl, kiraz ile süslenir.",
    "emoji": "🌿",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "orta",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-gin",
        "amount": "1 1/2 oz"
      },
      {
        "ingredientId": "bitter-orange",
        "amount": "1 dash",
        "optional": true
      },
      {
        "ingredientId": "citrus-orange",
        "amount": "Juice of 1/4",
        "optional": true
      },
      {
        "ingredientId": "garnish-cherry",
        "amount": "1",
        "optional": true
      }
    ],
    "steps": [
      "1. Tüm malzemeleri (kiraz hariç) buz ile çalkalayın ve bir kokteyl bardağına süzün.",
      "2. Kiraz ile süsleyin ve servis yapın."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:abbey-cocktail"
  },
  {
    "id": "cdb-abbey-martini",
    "name": "Abbey Martini",
    "description": "Ferahlık veren ve zarif bir tat profiline sahip martini.",
    "emoji": "🍸",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "orta",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-gin",
        "amount": "2 shots"
      },
      {
        "ingredientId": "liqueur-vermouth-sweet",
        "amount": "1 shot"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "1 shot"
      },
      {
        "ingredientId": "bitter-angostura",
        "amount": "3 dashes",
        "optional": true
      }
    ],
    "steps": [
      "1. Tüm malzemeleri bir shaker'a koyun ve karıştırın, ardından içeriği soğutulmuş bir kokteyl bardağına süzün."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:abbey-martini"
  },
  {
    "id": "cdb-abc",
    "name": "ABC",
    "description": "Tatlı ve yoğun bir shot, katmanlı sunumu ile dikkat çeker.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "1/3"
      },
      {
        "ingredientId": "liqueur-baileys",
        "amount": "1/3"
      },
      {
        "ingredientId": "spirit-cognac",
        "amount": "1/3"
      }
    ],
    "steps": [
      "1. Shot bardağında katmanlı olarak hazırlayın."
    ],
    "tags": [
      "shot",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:abc"
  },
  {
    "id": "cdb-abilene",
    "name": "Abilene",
    "description": "Ferahlatıcı ve hafif bir içecek, buz ile dolu bir bardakta servis edilir.",
    "emoji": "🍹",
    "technique": "stir",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-rum-dark",
        "amount": "1 1/2 oz"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "3 oz"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri neredeyse buz dolu bir highball bardağına dökün.",
      "2. İyice karıştırın."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:abilene"
  },
  {
    "id": "cdb-absolut-evergreen",
    "name": "Absolut Evergreen",
    "description": "Ferah ve hafif acı bir tat, Bitter Lemon ile tamamlanır.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-vodka",
        "amount": "2/3 part"
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "tatlandırıcı"
      }
    ],
    "steps": [
      "1. Karıştırın, buz üzerine dökün ve Bitter Lemon ile tamamlayın."
    ],
    "tags": [
      "other / unknown",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:absolut-evergreen"
  },
  {
    "id": "cdb-absolut-limousine",
    "name": "Absolut limousine",
    "description": "Tatlı ve ferah bir içecek, lime ile zenginleştirilmiştir.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-vodka",
        "amount": "2/3"
      },
      {
        "ingredientId": "citrus-lime",
        "amount": "1/3"
      },
      {
        "ingredientId": "mixer-tonic",
        "amount": "Top it up with"
      }
    ],
    "steps": [
      "1. Absolut'u bir bardağa doldurun.",
      "2. Lime suyu ekleyin.",
      "3. Buz ve lime dilimleri ekleyin."
    ],
    "tags": [
      "other / unknown",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:absolut-limousine"
  },
  {
    "id": "cdb-absolut-sex",
    "name": "Absolut Sex",
    "description": "Tatlı ve meyveli bir kokteyl, enerjik bir tat sunar.",
    "emoji": "💗",
    "technique": "shake",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-melon",
        "amount": "3/4 oz"
      },
      {
        "ingredientId": "mixer-cranberry",
        "amount": "1 oz"
      },
      {
        "ingredientId": "mixer-lemon-lime-soda",
        "amount": "1 splash"
      }
    ],
    "steps": [
      "1. Absolut Kurant, Midori ve Cranberry suyunu buz ile shaker'da çalkalayın: Rocks bardağına süzün: Üzerine biraz seven ekleyin."
    ],
    "tags": [
      "shot",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:absolut-sex"
  },
  {
    "id": "cdb-absolut-stress-2",
    "name": "Absolut Stress #2",
    "description": "Tatlı ve meyveli bir karışım, narenciye ile süslenir.",
    "emoji": "💗",
    "technique": "build",
    "glass": "highball",
    "difficulty": "orta",
    "prepTimeMinutes": 3,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-vodka",
        "amount": "1 1/2 oz"
      },
      {
        "ingredientId": "liqueur-peach",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "liqueur-coconut",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "mixer-cranberry",
        "amount": "1 1/2 oz"
      },
      {
        "ingredientId": "mixer-pineapple",
        "amount": "1 1/2 oz"
      }
    ],
    "steps": [
      "1. İyice karıştırın.",
      "2. Portakal ve kiraz ile süsleyin.",
      "3. Tadını çıkarın."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:absolut-stress-2"
  },
  {
    "id": "cdb-absolut-summertime",
    "name": "Absolut Summertime",
    "description": "Ferah ve tatlı bir yaz kokteyli, limon ile dengelenmiş.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "highball",
    "difficulty": "orta",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-vodka",
        "amount": "1 1/2 oz"
      },
      {
        "ingredientId": "mixer-lemon-lime-soda",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "mixer-soda",
        "amount": "3 oz"
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "1 slice"
      }
    ],
    "steps": [
      "1. Bütün malzemeleri limon hariç buz dolu bir shaker'a ekleyin.",
      "2. Kapatın ve kuvvetlice çalkalayın.",
      "3. Karışımı buz dolu bir Collins bardağına süzün.",
      "4. Limon ile süsleyin."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:absolut-summertime"
  },
  {
    "id": "cdb-absolutely-cranberry-smash",
    "name": "Absolutely Cranberry Smash",
    "description": "Tatlı ve ekşi bir karışım, ferahlatıcı bir içecek.",
    "emoji": "💗",
    "technique": "stir",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-vodka",
        "amount": "2 oz"
      },
      {
        "ingredientId": "mixer-cranberry",
        "amount": "4 oz"
      },
      {
        "ingredientId": "mixer-ginger-beer",
        "amount": "2 oz"
      }
    ],
    "steps": [
      "1. Malzemeleri bir arada karıştırın.",
      "2. Buz üzerinde servis edin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:absolutely-cranberry-smash"
  },
  {
    "id": "cdb-absolutely-fabulous",
    "name": "Absolutely Fabulous",
    "description": "Tatlı ve şampanya ile zenginleştirilmiş, zarif bir kokteyl.",
    "emoji": "🥂",
    "technique": "shake",
    "glass": "flute",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-vodka",
        "amount": "1 shot"
      },
      {
        "ingredientId": "mixer-cranberry",
        "amount": "2 shots"
      },
      {
        "ingredientId": "wine-champagne",
        "amount": "Top up with"
      }
    ],
    "steps": [
      "1. Vodka ve kızılcık suyunu bir shaker'da karıştırın ve bir bardağa süzün.",
      "2. Üzerine şampanya ekleyin."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:absolutely-fabulous"
  },
  {
    "id": "cdb-absolutly-screwed-up",
    "name": "Absolutly Screwed Up",
    "description": "Yoğun ve eğlenceli bir içecek, partiler için ideal.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "highball",
    "difficulty": "orta",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-vodka",
        "amount": "1 shot"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "1 shot"
      },
      {
        "ingredientId": "liqueur-triple-sec",
        "amount": "1 shot"
      },
      {
        "ingredientId": "mixer-ginger-beer",
        "amount": "Fill to top"
      }
    ],
    "steps": [
      "1. Daha iyi tat için çalkalayın, ama isterseniz karıştırabilirsiniz.",
      "2. 6 tane içerseniz, geceyi sarhoş geçirebilirsiniz."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:absolutly-screwed-up"
  },
  {
    "id": "cdb-acapulco",
    "name": "Acapulco",
    "description": "Taze nane ile ferahlatıcı bir tropikal kokteyl.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "rocks",
    "difficulty": "orta",
    "prepTimeMinutes": 5,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-rum-white",
        "amount": "1 1/2 oz"
      },
      {
        "ingredientId": "liqueur-triple-sec",
        "amount": "1 1/2 tsp"
      },
      {
        "ingredientId": "citrus-lime",
        "amount": "1 tblsp"
      },
      {
        "ingredientId": "garnish-sugar",
        "amount": "1 tsp",
        "optional": true
      },
      {
        "ingredientId": "garnish-mint",
        "amount": "1",
        "optional": true
      }
    ],
    "steps": [
      "1. Tüm malzemeleri (nane hariç) buz ile birleştirip çalkalayın ve bir eski moda bardağa süzün.",
      "2. Nane dalını ekleyin ve servis edin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:acapulco"
  },
  {
    "id": "cdb-acid",
    "name": "ACID",
    "description": "Ateşli ve yoğun bir içecek, cesur tatlar arayanlar için.",
    "emoji": "🥃",
    "technique": "build",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-rum-dark",
        "amount": "1 oz Bacardi"
      },
      {
        "ingredientId": "spirit-bourbon",
        "amount": "1 oz"
      }
    ],
    "steps": [
      "1. Önce 151'i, ardından 101'i dökün ve bir Coke veya Dr Pepper ile servis edin."
    ],
    "tags": [
      "shot",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:acid"
  },
  {
    "id": "cdb-adam",
    "name": "Adam",
    "description": "Tatlı ve dengeli bir kokteyl, klasik bir lezzet.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-rum-dark",
        "amount": "2 oz"
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "1 oz"
      },
      {
        "ingredientId": "sweet-grenadine",
        "amount": "1 tsp"
      }
    ],
    "steps": [
      "1. Buz dolu bir shaker'a tüm malzemeleri ekleyin.",
      "2. İyice çalkalayın.",
      "3. Bir kokteyl bardağına süzün."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:adam"
  },
  {
    "id": "cdb-adam-eve",
    "name": "Adam & Eve",
    "description": "Tatlı ve ferahlatıcı bir karışım, romantik bir içecek.",
    "emoji": "🌿",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "orta",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-gin",
        "amount": "1 shot"
      },
      {
        "ingredientId": "spirit-cognac",
        "amount": "1 shot"
      },
      {
        "ingredientId": "liqueur-creme-de-cacao",
        "amount": "1 shot"
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "1/8 shot"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri çalkalayın ve soğuk bir bardağa süzün."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:adam-eve"
  },
  {
    "id": "cdb-adam-bomb",
    "name": "Adam Bomb",
    "description": "Yoğun ve meyvemsi bir tat profiline sahip, ferahlatıcı bir kokteyl.",
    "emoji": "🌵",
    "technique": "blend",
    "glass": "coupe",
    "difficulty": "orta",
    "prepTimeMinutes": 6,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-rum-white",
        "amount": "1 part"
      },
      {
        "ingredientId": "spirit-vodka",
        "amount": "1 part"
      },
      {
        "ingredientId": "spirit-tequila",
        "amount": "1 part"
      },
      {
        "ingredientId": "liqueur-triple-sec",
        "amount": "1/2 part"
      },
      {
        "ingredientId": "garnish-salt",
        "amount": "1-3 pint",
        "optional": true
      }
    ],
    "steps": [
      "1. Buz ekleyin, ardından meyve ve meyve suyu ekleyin, ardından Rom, Vodka, Tekila ve triple sec ekleyin.",
      "2. Pürüzsüz olana kadar karıştırın, bardağın kenarını şeker veya tuzla kaplayın ve karışımı dökün.",
      "3. Limon veya lime dilimi ile süsleyin."
    ],
    "tags": [
      "punch / party drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:adam-bomb"
  },
  {
    "id": "cdb-adam-sunrise",
    "name": "Adam Sunrise",
    "description": "Tatlı ve ferahlatıcı bir içecek, yaz günleri için ideal.",
    "emoji": "🍹",
    "technique": "blend",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 5,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-vodka",
        "amount": "1/2"
      },
      {
        "ingredientId": "mixer-lemon-lime-soda",
        "amount": "1/2 can"
      },
      {
        "ingredientId": "garnish-sugar",
        "amount": "10 tsp",
        "optional": true
      }
    ],
    "steps": [
      "1. Blenderi buzla doldurun.",
      "2. Yarım bardak Bartons Vodka ekleyin.",
      "3. 10 tatlı kaşığı şeker ekleyin, 1/2 kutu limonata konsantresi ekleyin ve su ile doldurun.",
      "4. 60 saniye karıştırın."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:adam-sunrise"
  },
  {
    "id": "cdb-addington",
    "name": "Addington",
    "description": "Hafif ve ferahlatıcı bir kokteyl, vermutların uyumunu sunar.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-vermouth-sweet",
        "amount": "2 shots"
      },
      {
        "ingredientId": "liqueur-vermouth-dry",
        "amount": "1 shot"
      },
      {
        "ingredientId": "mixer-soda",
        "amount": "Top up with"
      }
    ],
    "steps": [
      "1. İki vermutu bir şakere karıştırın ve soğuk bir bardağa süzün.",
      "2. Soda suyu ile tamamlayın."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:addington"
  },
  {
    "id": "cdb-addison",
    "name": "Addison",
    "description": "Hafif ve dengeli bir tat sunan, klasik bir kokteyl.",
    "emoji": "🌿",
    "technique": "shake",
    "glass": "martini",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-gin",
        "amount": "1 1/2 shot"
      },
      {
        "ingredientId": "liqueur-vermouth-sweet",
        "amount": "1 1/2 shot"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri karıştırın ve soğuk bir bardağa süzün."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:addison"
  },
  {
    "id": "cdb-addison-special",
    "name": "Addison Special",
    "description": "Tatlı ve meyvemsi bir lezzet sunan, özel bir kokteyl.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-vodka",
        "amount": "1 shot"
      },
      {
        "ingredientId": "sweet-grenadine",
        "amount": "1 tblsp"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "Fill with"
      }
    ],
    "steps": [
      "1. Malzemeleri listedeki sırayla bir şakere ekleyin.",
      "2. Yarım dolu buz ile doldurun ve iyice çalkalayın.",
      "3. Buzlu bir bardağa süzün ve bir kiraz ve portakal dilimi ile süsleyin."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:addison-special"
  },
  {
    "id": "cdb-adios-amigos-cocktail",
    "name": "Adios Amigos Cocktail",
    "description": "Tatlı ve ferah bir içecek, arkadaşlarla paylaşmak için ideal.",
    "emoji": "🌿",
    "technique": "shake",
    "glass": "martini",
    "difficulty": "zor",
    "prepTimeMinutes": 6,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-rum-white",
        "amount": "1 shot"
      },
      {
        "ingredientId": "liqueur-vermouth-dry",
        "amount": "1/2 shot"
      },
      {
        "ingredientId": "spirit-cognac",
        "amount": "1/2 shot"
      },
      {
        "ingredientId": "spirit-gin",
        "amount": "1/2 shot"
      },
      {
        "ingredientId": "citrus-lime",
        "amount": "1/4 shot"
      },
      {
        "ingredientId": "sweet-simple-syrup",
        "amount": "1/4 shot"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri karıştırın ve soğuk bir bardağa süzün."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:adios-amigos-cocktail"
  },
  {
    "id": "cdb-adonis-cocktail",
    "name": "Adonis Cocktail",
    "description": "Hafif ve zarif bir tat sunan, klasik bir kokteyl.",
    "emoji": "🍹",
    "technique": "stir",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-vermouth-sweet",
        "amount": "3/4 oz"
      },
      {
        "ingredientId": "bitter-orange",
        "amount": "1 dash",
        "optional": true
      }
    ],
    "steps": [
      "1. Tüm malzemeleri buz ile karıştırın, içeriği bir kokteyl bardağına süzün ve servis edin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:adonis-cocktail"
  },
  {
    "id": "cdb-affair",
    "name": "Affair",
    "description": "Tatlı ve meyvemsi bir karışım, ferahlatıcı bir içecek.",
    "emoji": "💗",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "2 oz"
      },
      {
        "ingredientId": "mixer-cranberry",
        "amount": "2 oz"
      },
      {
        "ingredientId": "mixer-soda",
        "amount": "tatlandırıcı"
      }
    ],
    "steps": [
      "1. Schnapps, portakal suyu ve kızılcık suyunu bir yüksekball bardağına buz üzerine dökün.",
      "2. Kulüp sodası ile tamamlayın ve servis edin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:affair"
  },
  {
    "id": "cdb-affinity",
    "name": "Affinity",
    "description": "Affinity, dengeli ve hafif acı bir tat profiline sahip zarif bir kokteyl.",
    "emoji": "🥃",
    "technique": "stir",
    "glass": "coupe",
    "difficulty": "orta",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-scotch",
        "amount": "1 1/2 oz"
      },
      {
        "ingredientId": "liqueur-vermouth-sweet",
        "amount": "1 oz"
      },
      {
        "ingredientId": "liqueur-vermouth-dry",
        "amount": "1 oz"
      },
      {
        "ingredientId": "bitter-orange",
        "amount": "2 dashes",
        "optional": true
      }
    ],
    "steps": [
      "1. Buz dolu bir karıştırma bardağında tüm malzemeleri birleştirin.",
      "2. İyice karıştırın.",
      "3. Kokteyl bardağına süzün."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:affinity"
  },
  {
    "id": "cdb-after-dinner-cocktail",
    "name": "After Dinner Cocktail",
    "description": "After Dinner Cocktail, tatlı ve ferahlatıcı bir içecek olarak ideal bir kapanıştır.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-cognac",
        "amount": "1 oz"
      },
      {
        "ingredientId": "liqueur-triple-sec",
        "amount": "1 oz"
      },
      {
        "ingredientId": "citrus-lime",
        "amount": "Juice of 1"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri (lime dilimi hariç) buzla çalkalayın ve kokteyl bardağına süzün.",
      "2. Lime dilimini ekleyin ve servis yapın."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:after-dinner-cocktail"
  },
  {
    "id": "cdb-after-five",
    "name": "After Five",
    "description": "After Five, tatlı ve yoğun katmanlarıyla eğlenceli bir shot deneyimi sunar.",
    "emoji": "☕",
    "technique": "build",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-coffee",
        "amount": "tatlandırıcı"
      },
      {
        "ingredientId": "liqueur-baileys",
        "amount": "tatlandırıcı"
      }
    ],
    "steps": [
      "1. Kahlua'yı shot bardağına yarıya kadar dökün.",
      "2. Bir kaşık kullanarak, yavaşça Peppermint Schnapps'ı ekleyin.",
      "3. Yine bir kaşık kullanarak, Bailey's ile bardağı doldurun.",
      "4. Hepsini bir anda içerek Peppermint Pattie tadını alın!"
    ],
    "tags": [
      "shot",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:after-five"
  },
  {
    "id": "cdb-after-sex",
    "name": "After sex",
    "description": "After Sex, tatlı ve meyvemsi bir karışım ile ferahlatıcı bir içecek sunar.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-vodka",
        "amount": "2 cl"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "tatlandırıcı"
      }
    ],
    "steps": [
      "1. Vodka ve kremayı buz dolu bir uzun bardağa dökün ve meyve suyu ile doldurun.",
      "2. Üst kısmını grenadin ve şekerle süsleyin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:after-sex"
  },
  {
    "id": "cdb-after-supper-cocktail",
    "name": "After Supper Cocktail",
    "description": "After Supper Cocktail, hafif ve ferahlatıcı bir içecek olarak akşam yemeklerinin ardından idealdir.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-triple-sec",
        "amount": "1 oz"
      },
      {
        "ingredientId": "spirit-cognac",
        "amount": "1 oz"
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "1/2 tsp"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri buzla çalkalayın, kokteyl bardağına süzün ve servis yapın."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:after-supper-cocktail"
  },
  {
    "id": "cdb-afternoon",
    "name": "Afternoon",
    "description": "Afternoon, yoğun ve kremsi bir tat ile dinlendirici bir içecek sunar.",
    "emoji": "☕",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-coffee",
        "amount": "1 cl"
      },
      {
        "ingredientId": "liqueur-baileys",
        "amount": "1 cl"
      },
      {
        "ingredientId": "mixer-espresso",
        "amount": "4 cl hot"
      }
    ],
    "steps": [
      "1. Uygun bir bardağa buz koymadan hazırlayın.",
      "2. İstenirse üstüne krema ekleyin.",
      "3. Doğrudan servis yapın."
    ],
    "tags": [
      "coffee / tea",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:afternoon"
  },
  {
    "id": "cdb-alabama-slammer",
    "name": "Alabama Slammer",
    "description": "Alabama Slammer, tatlı ve meyvemsi bir karışım ile enerjik bir içecek sunar.",
    "emoji": "🌿",
    "technique": "stir",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "1 oz"
      },
      {
        "ingredientId": "spirit-gin",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "1 dash"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri (limon suyu hariç) buzla dolu bir highball bardağına dökün.",
      "2. Karıştırın, bir damla limon suyu ekleyin ve servis yapın."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:alabama-slammer"
  },
  {
    "id": "cdb-alaska-cocktail",
    "name": "Alaska Cocktail",
    "description": "Alaska Cocktail, hafif ve ferahlatıcı bir tat ile zarif bir içecek deneyimi sunar.",
    "emoji": "🌿",
    "technique": "stir",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "bitter-orange",
        "amount": "2 dashes",
        "optional": true
      },
      {
        "ingredientId": "spirit-gin",
        "amount": "1 1/2 oz"
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "Twist of"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri buzla karıştırın, içeriği kokteyl bardağına süzün.",
      "2. Üzerine bir limon kabuğu ekleyin ve servis yapın."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:alaska-cocktail"
  },
  {
    "id": "cdb-alexander",
    "name": "Alexander",
    "description": "Zengin ve kremsi bir tat profiline sahip, hafif baharatlı bir kokteyl.",
    "emoji": "🌿",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-gin",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "liqueur-creme-de-cacao",
        "amount": "1/2 oz white"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri buzla çalkalayın ve bir kokteyl bardağına süzün.",
      "2. Üzerine muskat serpin ve servis edin."
    ],
    "tags": [
      "ordinary drink",
      "iba"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:alexander"
  },
  {
    "id": "cdb-alfie-cocktail",
    "name": "Alfie Cocktail",
    "description": "Tatlı ve ferah bir içecek, dengeli bir lezzet sunar.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "citrus-lemon",
        "amount": "1 1/2 oz"
      },
      {
        "ingredientId": "liqueur-triple-sec",
        "amount": "1 dash"
      },
      {
        "ingredientId": "mixer-pineapple",
        "amount": "1 tblsp"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri buzla birleştirip çalkalayın, kokteyl bardağına süzün ve servis edin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:alfie-cocktail"
  },
  {
    "id": "cdb-algonquin",
    "name": "Algonquin",
    "description": "Hafif ekşi ve tatlı bir dengeye sahip, ferahlatıcı bir kokteyl.",
    "emoji": "🥃",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-bourbon",
        "amount": "1 1/2 oz"
      },
      {
        "ingredientId": "liqueur-vermouth-dry",
        "amount": "1 oz"
      },
      {
        "ingredientId": "mixer-pineapple",
        "amount": "1 oz"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri buzla birleştirip çalkalayın, kokteyl bardağına süzün ve servis edin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:algonquin"
  },
  {
    "id": "cdb-alice-in-wonderland",
    "name": "Alice in Wonderland",
    "description": "Tatlı ve renkli bir içecek, eğlenceli bir deneyim sunar.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "1 shot"
      },
      {
        "ingredientId": "liqueur-triple-sec",
        "amount": "1 shot"
      }
    ],
    "steps": [
      "1. Üç malzemeyi eşit oranlarda karıştırın."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:alice-in-wonderland"
  },
  {
    "id": "cdb-allegheny",
    "name": "Allegheny",
    "description": "Yoğun ve aromatik bir tat profili, limon kabuğuyla ferahlatır.",
    "emoji": "🥃",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "orta",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-vermouth-dry",
        "amount": "1 oz"
      },
      {
        "ingredientId": "spirit-bourbon",
        "amount": "1 oz"
      },
      {
        "ingredientId": "spirit-cognac",
        "amount": "1 1/2 tsp"
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "1 1/2 tsp"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri (limon kabuğu hariç) buzla çalkalayın ve bir kokteyl bardağına süzün.",
      "2. Limon kabuğu ile süsleyin ve servis edin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:allegheny"
  },
  {
    "id": "cdb-allies-cocktail",
    "name": "Allies Cocktail",
    "description": "Hafif acı ve tatlı bir denge sunan, klasik bir kokteyl.",
    "emoji": "🌿",
    "technique": "stir",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-vermouth-dry",
        "amount": "1 oz"
      },
      {
        "ingredientId": "spirit-gin",
        "amount": "1 oz"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri buzla karıştırın, kokteyl bardağına süzün ve servis edin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:allies-cocktail"
  },
  {
    "id": "cdb-almeria",
    "name": "Almeria",
    "description": "Tatlı ve kremsi bir içecek, keyifli bir deneyim sağlar.",
    "emoji": "☕",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-rum-dark",
        "amount": "2 oz"
      },
      {
        "ingredientId": "liqueur-coffee",
        "amount": "1 oz"
      }
    ],
    "steps": [
      "1. Buz dolu bir shaker'a tüm malzemeleri ekleyin.",
      "2. İyice çalkalayın.",
      "3. Kokteyl bardağına süzün."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:almeria"
  },
  {
    "id": "cdb-almond-chocolate-coffee",
    "name": "Almond Chocolate Coffee",
    "description": "Tatlı ve yoğun bir kahve deneyimi, çikolata ile zenginleştirilmiş.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "3/4 oz"
      },
      {
        "ingredientId": "liqueur-creme-de-cacao",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "mixer-espresso",
        "amount": "8 oz"
      }
    ],
    "steps": [
      "1. Sırasıyla kahve fincanına dökün.",
      "2. Üzerine çırpılmış krema ve çikolata parçaları ekleyin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:almond-chocolate-coffee"
  },
  {
    "id": "cdb-almond-joy",
    "name": "Almond Joy",
    "description": "Tatlı ve yoğun bir çikolata ve badem aroması sunar.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "liqueur-creme-de-cacao",
        "amount": "1/2 oz white"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri buzla çalkalayın, kokteyl bardağına süzün ve servis edin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:almond-joy"
  },
  {
    "id": "cdb-amaretto-and-cream",
    "name": "Amaretto And Cream",
    "description": "Kremalı ve tatlı bir lezzet sunar, yumuşak bir içim sağlar.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "1 1/2 oz"
      }
    ],
    "steps": [
      "1. Kırık buz ile iyice çalkalayın, içeriği kokteyl bardağına süzün ve servis edin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:amaretto-and-cream"
  },
  {
    "id": "cdb-amaretto-fizz",
    "name": "Amaretto fizz",
    "description": "Ferahlatıcı ve meyvemsi bir tat sunar, gazlı içecek ile dengelenir.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "4 cl"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "6 cl"
      },
      {
        "ingredientId": "citrus-orange",
        "amount": "Garnish with",
        "optional": true
      }
    ],
    "steps": [
      "1. Amaretto, portakal suyu ve köpüklü şarabı bir sürahiye karıştırın.",
      "2. İsterseniz her bardağa bir dilim portakal kabuğu ekleyin."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:amaretto-fizz"
  },
  {
    "id": "cdb-amaretto-mist",
    "name": "Amaretto Mist",
    "description": "Serinletici ve hafif bir içim sunar, limon aroması ile zenginleşir.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "1 1/2 oz"
      },
      {
        "ingredientId": "citrus-lime",
        "amount": "1"
      }
    ],
    "steps": [
      "1. Amarettoyu bir eski moda bardağa ezilmiş buz üzerine dökün.",
      "2. Lime dilimini ekleyin ve servis edin.",
      "3. İsterseniz lime yerine limon dilimi kullanabilirsiniz."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:amaretto-mist"
  },
  {
    "id": "cdb-amaretto-rose",
    "name": "Amaretto Rose",
    "description": "Tatlı ve ferah bir içim sunar, soda ile hafifletilir.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "1 1/2 oz"
      },
      {
        "ingredientId": "citrus-lime",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "mixer-soda",
        "amount": "tatlandırıcı"
      }
    ],
    "steps": [
      "1. Amaretto ve lime suyunu bir collins bardağına buz üzerine dökün.",
      "2. Kulüp sodası ile doldurun ve servis edin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:amaretto-rose"
  },
  {
    "id": "cdb-amaretto-shake",
    "name": "Amaretto Shake",
    "description": "Zengin ve tatlı bir lezzet sunar, çikolata ile süslenir.",
    "emoji": "🍹",
    "technique": "blend",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 5,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-cognac",
        "amount": "2 oz"
      },
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "2 oz"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri bir blenderda birleştirin ve pürüzsüz olana kadar yüksek hızda karıştırın.",
      "2. Soğutulmuş bardakta acımsı çikolata rendesi ile süsleyerek servis edin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:amaretto-shake"
  },
  {
    "id": "cdb-amaretto-sour",
    "name": "Amaretto Sour",
    "description": "Tatlı ve ekşi bir denge sunar, meyve ile zenginleştirilir.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "1 1/2 oz"
      }
    ],
    "steps": [
      "1. Çalkalayın ve süzün.",
      "2. Bir kiraz ve bir portakal dilimi ile süsleyin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:amaretto-sour"
  },
  {
    "id": "cdb-amaretto-stinger",
    "name": "Amaretto Stinger",
    "description": "Tatlı ve yoğun bir lezzet sunar, ferahlatıcı bir içim sağlar.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "1 1/2 oz"
      },
      {
        "ingredientId": "liqueur-creme-de-cacao",
        "amount": "3/4 oz"
      }
    ],
    "steps": [
      "1. Malzemeleri kırık buz ile iyice çalkalayın, kokteyl bardağına süzün ve servis edin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:amaretto-stinger"
  },
  {
    "id": "cdb-amaretto-stone-sour",
    "name": "Amaretto Stone Sour",
    "description": "Tatlı ve ekşi dengesiyle ferahlatıcı bir içecek.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "1 part"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "1 part"
      }
    ],
    "steps": [
      "1. Karıştırın ve buz üzerinde servis yapın."
    ],
    "tags": [
      "other / unknown",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:amaretto-stone-sour"
  },
  {
    "id": "cdb-amaretto-stone-sour-alternative",
    "name": "Amaretto Stone Sour Alternative",
    "description": "Tatlı ve ekşi notalarıyla zengin bir alternatif.",
    "emoji": "🌵",
    "technique": "shake",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "2 oz"
      },
      {
        "ingredientId": "spirit-tequila",
        "amount": "2 oz"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "Add splash"
      }
    ],
    "steps": [
      "1. Ekşi karışımı, tekila ve amarettoyu buzla çalkalayın.",
      "2. Yüksek bardak içine süzün.",
      "3. Üzerine bir miktar portakal suyu ekleyin.",
      "4. Portakal dilimi ve kiraz ile süsleyin."
    ],
    "tags": [
      "other / unknown",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:amaretto-stone-sour-alternative"
  },
  {
    "id": "cdb-amaretto-sunrise",
    "name": "Amaretto Sunrise",
    "description": "Tatlı ve meyvemsi bir içecek, güneş doğuşunu andırıyor.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "1 cl"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "4 oz"
      },
      {
        "ingredientId": "sweet-grenadine",
        "amount": "1/4 cl"
      }
    ],
    "steps": [
      "1. Amarettoyu ve portakal suyunu karıştırın.",
      "2. Bardağa dökün ve ardından grenadin ekleyin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:amaretto-sunrise"
  },
  {
    "id": "cdb-amaretto-sunset",
    "name": "Amaretto Sunset",
    "description": "Tatlı ve ferahlatıcı bir içecek, gün batımını simgeliyor.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-triple-sec",
        "amount": "1/2 jigger"
      },
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "3 shots"
      }
    ],
    "steps": [
      "1. Malzemeleri barmen karıştırıcısında hızlıca çalkalayın.",
      "2. Buzları süzün, hemen bir dilim portakal ile servis yapın."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:amaretto-sunset"
  },
  {
    "id": "cdb-amaretto-sweet-sour",
    "name": "Amaretto Sweet & Sour",
    "description": "Tatlı ve ekşi karışımıyla yoğun bir içecek.",
    "emoji": "🍹",
    "technique": "blend",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 5,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "tatlandırıcı"
      },
      {
        "ingredientId": "liqueur-melon",
        "amount": "tatlandırıcı"
      },
      {
        "ingredientId": "mixer-pineapple",
        "amount": "tatlandırıcı"
      }
    ],
    "steps": [
      "1. Karıştırıcıyı 3/4 buz ile doldurun.",
      "2. Üzerine tatlı ve ekşi karışım ekleyin.",
      "3. Ananas suyu, kavun likörü ve amaretto ekleyin.",
      "4. Karışımı margarita kıvamına gelene kadar karıştırın."
    ],
    "tags": [
      "punch / party drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:amaretto-sweet-sour"
  },
  {
    "id": "cdb-amaretto-tea",
    "name": "Amaretto Tea",
    "description": "Sıcak çay ve amaretto ile zenginleştirilmiş rahatlatıcı bir içecek.",
    "emoji": "🍹",
    "technique": "stir",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-amaretto",
        "amount": "2 oz"
      }
    ],
    "steps": [
      "1. Sıcak çayı pousse-cafe bardağına dökün.",
      "2. Amarettoyu ekleyin, karıştırmayın.",
      "3. Üzerine soğuk krema ekleyin ve servis yapın."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:amaretto-tea"
  },
  {
    "id": "cdb-americano",
    "name": "Americano",
    "description": "Acı ve tatlı notalarla dengeli bir aperitif.",
    "emoji": "🟥",
    "technique": "build",
    "glass": "highball",
    "difficulty": "orta",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-campari",
        "amount": "1 oz"
      },
      {
        "ingredientId": "liqueur-vermouth-sweet",
        "amount": "1 oz red"
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "Twist of"
      },
      {
        "ingredientId": "citrus-orange",
        "amount": "Twist of",
        "optional": true
      }
    ],
    "steps": [
      "1. Campari ve vermutu buz üzerine dökün, soda suyu ekleyin ve portakal dilimi ile süsleyin."
    ],
    "tags": [
      "ordinary drink",
      "iba"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:americano"
  },
  {
    "id": "cdb-angel-face",
    "name": "Angel Face",
    "description": "Tatlı ve meyvemsi bir karışım, hafif ve zarif.",
    "emoji": "🌿",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-cognac",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "spirit-gin",
        "amount": "1 oz"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri buz ile çalkalayın ve kokteyl bardağına süzün."
    ],
    "tags": [
      "ordinary drink",
      "iba"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:angel-face"
  },
  {
    "id": "cdb-aperol-spritz",
    "name": "Aperol Spritz",
    "description": "Ferah ve hafif acımsı bir tat profiline sahip, yaz kokteyli.",
    "emoji": "🧡",
    "technique": "build",
    "glass": "wine",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-aperol",
        "amount": "100 ml"
      },
      {
        "ingredientId": "wine-prosecco",
        "amount": "150 ml"
      },
      {
        "ingredientId": "mixer-soda",
        "amount": "Top"
      }
    ],
    "steps": [
      "1. İki bardağa birkaç buz küpü koyun ve her birine 50 ml Aperol ekleyin.",
      "2. Bardaklara prosecco dökün ve isterseniz soda ile tamamlayın."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:aperol-spritz"
  },
  {
    "id": "cdb-apple-grande",
    "name": "Apple Grande",
    "description": "Tatlı ve ferah bir içecek, elma tadıyla dolu.",
    "emoji": "🌵",
    "technique": "build",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-tequila",
        "amount": "3 oz"
      }
    ],
    "steps": [
      "1. Her iki malzemeyi soğutun!! Bir tumblerda karıştırın ve tadını çıkarın!"
    ],
    "tags": [
      "punch / party drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:apple-grande"
  },
  {
    "id": "cdb-apple-highball",
    "name": "Apple Highball",
    "description": "Ferahlık veren, hafif tatlı ve meyveli bir kokteyl.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "citrus-lime",
        "amount": "Chopped"
      },
      {
        "ingredientId": "spirit-cognac",
        "amount": "1 shot"
      }
    ],
    "steps": [
      "1. Bir highball bardağa buz ekleyin.",
      "2. Taze lime dilimini kenarına sürün ve bardağa yerleştirin.",
      "3. Bir shot elma schnapps, bir shot Courvoisier ekleyin ve zencefilli gazoz ile tamamlayın."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:apple-highball"
  },
  {
    "id": "cdb-apple-pie-with-a-crust",
    "name": "Apple Pie with A Crust",
    "description": "Tatlı ve baharatlı, elmalı turta tadında bir kokteyl.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "highball",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-coconut",
        "amount": "1 part"
      }
    ],
    "steps": [
      "1. İki sıvıyı karıştırın ve üzerine tarçın serpin.",
      "2. Soğuk veya ısıtılmış olarak servis edin."
    ],
    "tags": [
      "other / unknown",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:apple-pie-with-a-crust"
  },
  {
    "id": "cdb-apple-slammer",
    "name": "Apple Slammer",
    "description": "Hızlı ve eğlenceli, tatlı bir shot deneyimi.",
    "emoji": "🍹",
    "technique": "build",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "mixer-lemon-lime-soda",
        "amount": "1 part"
      }
    ],
    "steps": [
      "1. Shot bardağına dökün ve tüketiciye sunun, üstünü avuçlarıyla kapatması beklenir, bardağı kaldırıp masaya vurmalı ve hızlıca yutmalıdır."
    ],
    "tags": [
      "shot",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:apple-slammer"
  },
  {
    "id": "cdb-applecar",
    "name": "Applecar",
    "description": "Tatlı ve ferahlatıcı, elma aromalı bir kokteyl.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "liqueur-triple-sec",
        "amount": "1 oz"
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "1 oz"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri buz ile çalkalayın, bir kokteyl bardağına süzün ve servis edin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:applecar"
  },
  {
    "id": "cdb-applejack",
    "name": "Applejack",
    "description": "Tatlı ve yoğun bir elma tadı sunan klasik bir kokteyl.",
    "emoji": "🥃",
    "technique": "build",
    "glass": "coupe",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-bourbon",
        "amount": "1 oz"
      },
      {
        "ingredientId": "liqueur-melon",
        "amount": "1/2 oz"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri karıştırma bardağına ekleyin, soğutun ve kokteyl bardağına süzün."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:applejack"
  },
  {
    "id": "cdb-apricot-lady",
    "name": "Apricot Lady",
    "description": "Tatlı ve meyvemsi, kremsi bir dokuya sahip zarif bir kokteyl.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "rocks",
    "difficulty": "orta",
    "prepTimeMinutes": 5,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-rum-white",
        "amount": "1 1/2 oz"
      },
      {
        "ingredientId": "spirit-cognac",
        "amount": "1 oz"
      },
      {
        "ingredientId": "liqueur-triple-sec",
        "amount": "1 tsp"
      },
      {
        "ingredientId": "citrus-lemon",
        "amount": "1/2 oz"
      },
      {
        "ingredientId": "citrus-orange",
        "amount": "1",
        "optional": true
      }
    ],
    "steps": [
      "1. Buz küpleriyle yarı dolu bir shakerda rom, kayısı brendi, triple sec, limon suyu ve yumurta beyazını birleştirin.",
      "2. İyice çalkalayın.",
      "3. Eski tarz bir bardağa süzün ve neredeyse buz küpleriyle doldurun.",
      "4. Portakal dilimi ile süsleyin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:apricot-lady"
  },
  {
    "id": "cdb-apricot-punch",
    "name": "Apricot punch",
    "description": "Tatlı ve meyvemsi bir punch, ferahlatıcı bir yaz içeceği.",
    "emoji": "🥂",
    "technique": "build",
    "glass": "rocks",
    "difficulty": "orta",
    "prepTimeMinutes": 3,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-cognac",
        "amount": "1 qt"
      },
      {
        "ingredientId": "wine-champagne",
        "amount": "4 fifth"
      },
      {
        "ingredientId": "spirit-vodka",
        "amount": "1 fifth"
      },
      {
        "ingredientId": "mixer-lemon-lime-soda",
        "amount": "4 L"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "1/2 gal"
      }
    ],
    "steps": [
      "1. Tüm malzemeleri büyük bir punch kasesine dökün.",
      "2. Buz ve soyulmuş, dilimlenmiş 4 portakal ekleyin."
    ],
    "tags": [
      "punch / party drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:apricot-punch"
  },
  {
    "id": "cdb-aquamarine",
    "name": "Aquamarine",
    "description": "Ferahlık veren, hafif tatlı bir kokteyl, zarif bir sunumla.",
    "emoji": "🍹",
    "technique": "shake",
    "glass": "martini",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "mixer-pineapple",
        "amount": "1 oz"
      }
    ],
    "steps": [
      "1. Bir shaker içinde buz ile iyice çalkalayın.",
      "2. Martini bardağına süzün."
    ],
    "tags": [
      "cocktail",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:aquamarine"
  },
  {
    "id": "cdb-archbishop",
    "name": "Archbishop",
    "description": "Yoğun ve hafif acı bir tat profiline sahip klasik bir kokteyl.",
    "emoji": "🌿",
    "technique": "stir",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-gin",
        "amount": "2 oz"
      },
      {
        "ingredientId": "citrus-lime",
        "amount": "1"
      }
    ],
    "steps": [
      "1. Eski moda bir bardağı neredeyse buz küpleriyle doldurun, tüm malzemeleri ekleyin.",
      "2. İyice karıştırın."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:archbishop"
  },
  {
    "id": "cdb-arctic-fish",
    "name": "Arctic Fish",
    "description": "Yoğun ve serinletici bir içecek, tatlı ve tuzlu bir deniz deneyimi sunar.",
    "emoji": "🍹",
    "technique": "stir",
    "glass": "rocks",
    "difficulty": "kolay",
    "prepTimeMinutes": 4,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "spirit-vodka",
        "amount": "1/3 part"
      },
      {
        "ingredientId": "mixer-orange-juice",
        "amount": "1/3 part"
      }
    ],
    "steps": [
      "1. Bardağı buz ve balık ile doldurun, votka, üzüm sodası ve portakal suyu ekleyin.",
      "2. KARIŞTIRMAYIN!!!!! İyi soğutulmuş olarak servis edin."
    ],
    "tags": [
      "punch / party drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:arctic-fish"
  },
  {
    "id": "cdb-arise-my-love",
    "name": "Arise My Love",
    "description": "Tatlı ve ferahlatıcı bir şampanya kokteyli, romantik bir dokunuşla.",
    "emoji": "🥂",
    "technique": "build",
    "glass": "flute",
    "difficulty": "kolay",
    "prepTimeMinutes": 2,
    "servings": 1,
    "ingredients": [
      {
        "ingredientId": "wine-champagne",
        "amount": "Chilled"
      },
      {
        "ingredientId": "liqueur-creme-de-cacao",
        "amount": "1 tsp"
      }
    ],
    "steps": [
      "1. Şampanya kadehine krema de menthe ekleyin.",
      "2. Soğutulmuş şampanya ile doldurun ve servis edin."
    ],
    "tags": [
      "ordinary drink",
      "klasik"
    ],
    "source": "classic",
    "imageUrl": "cocktaildb:arise-my-love"
  }
];

export const COCKTAILDB_RECIPE_INDEX: Record<string, Cocktail> = Object.fromEntries(
  COCKTAILDB_RECIPES.map((c) => [c.id, c]),
);
