/**
 * Centralized Turkish UI copy. Keep tone warm, conversational, family-friendly.
 */
export const t = {
  app: {
    name: "SwipeBite",
    tagline: "Kaydır. Eşleş. Pişir.",
  },
  common: {
    continue: "Devam et",
    skip: "Geç",
    save: "Kaydet",
    cancel: "Vazgeç",
    done: "Tamam",
    back: "Geri",
    next: "İleri",
    retry: "Tekrar dene",
    loading: "Yükleniyor…",
    error: "Bir şeyler ters gitti",
  },
  auth: {
    welcomeTitle: "Bugün ne yesek?",
    welcomeSubtitle:
      "Ev halkıyla birlikte yemek kararını saniyeler içinde verin.",
    continueWithEmail: "E-posta ile devam et",
    continueWithGoogle: "Google ile devam et",
    continueWithApple: "Apple ile devam et",
    legal:
      "Devam ederek Kullanım Koşulları ve Gizlilik Politikası’nı kabul edersiniz.",
    emailPlaceholder: "E-posta adresin",
    namePlaceholder: "Adın",
    otpTitle: "Doğrulama kodu",
    otpSubtitle: (email: string) =>
      `${email} adresine 6 haneli bir kod gönderdik.`,
    otpPlaceholder: "6 haneli kod",
    sendCode: "Kod gönder",
    verifyCode: "Doğrula",
    resendCode: "Kodu tekrar gönder",
    codeSent: "Kod gönderildi. Gelen kutunu kontrol et.",
    invalidCode: "Kod hatalı veya süresi dolmuş.",
    invalidEmail: "Geçerli bir e-posta gir.",
  },
  onboarding: {
    step: (i: number, n: number) => `Adım ${i} / ${n}`,
    allergiesTitle: "Alerjin var mı?",
    allergiesSubtitle: "Sana hiçbir zaman yanlış öneri göndermeyelim.",
    dislikesTitle: "Sevmediklerin?",
    dislikesSubtitle: "Tabağında görmek istemediklerini seç.",
    spiceTitle: "Acılı seviyor musun?",
    spiceSubtitle: "Acı toleransını belirle, sana göre önerelim.",
    cuisinesTitle: "Hangi mutfak seni mutlu eder?",
    cuisinesSubtitle: "Birden fazla seçebilirsin.",
    householdTitle: "Evine bir isim ver",
    householdSubtitle: "Birlikte yemek kararı vereceğiniz alan burası.",
    householdPlaceholder: "Örn. Bizim Ev",
    invitePartnerTitle: "Eşini davet et",
    invitePartnerSubtitle: "Birlikte kaydırın, daha hızlı karar verin.",
    inviteViaLink: "Davet bağlantısı paylaş",
    inviteViaQr: "QR kod ile davet et",
    inviteLater: "Sonra yaparım",
    firstSessionTitle: "Hadi ilk eşleşmeyi bulalım",
    firstSessionSubtitle: "Birkaç kart kaydır, gerisini biz hallederiz.",
    startSwiping: "Kaydırmaya başla",
    barTitle: "Bar modu",
    barSubtitle:
      "Kokteyl tarifleri, bar dolabı önerileri ve alkollü içecek eşleştirmeleri. İstemezsen bu bölümü kapatabilirsin.",
    barConsent: "18 yaşından büyüğüm ve alkollü içerikleri görmek istiyorum.",
    barEnable: "Bar modunu aç",
    barSkip: "Şimdilik kapalı kalsın",
  },
  spice: {
    none: "Hiç acı sevmem",
    mild: "Az acılı",
    medium: "Orta",
    hot: "Bol acılı",
  },
  tabs: {
    home: "Ana sayfa",
    swipe: "Eşleş",
    plan: "Hafta",
    pantry: "Kiler",
    profile: "Profil",
    bar: "Bar",
  },
  home: {
    greetingMorning: "Günaydın",
    greetingDay: "Merhaba",
    greetingEvening: "İyi akşamlar",
    primaryCta: "Yemek eşleşmesi başlat",
    quickFromPantry: "Evdeki malzemelerle öner",
    quickWeekly: "Haftalık plan oluştur",
    quickImport: "Tarif içe aktar",
    quickSaved: "Kaydettiklerim",
    quickInfluencer: "Fenomen Tarifler",
    activeSessionTitle: "Aktif oturum",
    waitingPartner: "Eşinin oyu bekleniyor",
    matchReady: "Bugünün eşleşmesi bulundu",
    aiBubbleBusyWeek:
      "Bu hafta yoğun görünüyorsunuz. Hızlı tarifler önereyim mi?",
    aiBubbleNoSoup:
      "Bir süredir çorba içmediniz. Mercimek çorbası ister misiniz?",
    aiBubblePantry: "Kilerdeki malzemelerle 4 yemek yapabilirsin.",
  },
  swipe: {
    sessionTitle: "Akşam yemeği eşleşmesi",
    swipeHint: "Sağa kaydır beğen, sola kaydır geç",
    compatibility: "Ev uyumu",
    pantryMatch: "Kiler uyumu",
    prepTime: (m: number) => `${m} dk`,
    superlike: "Süper beğeni",
    explain: "Neden bu öneri?",
    emptyTitle: "Bugünlük bu kadar",
    emptySubtitle: "Yeni öneriler için biraz sonra dön ya da kileri güncelle.",
    refresh: "Yenile",
  },
  match: {
    title: "Eşleşme bulundu",
    subtitle: "Bugün için ev halkının ortak kararı:",
    whyMatched: "Neden eşleşti?",
    likedBy: "Beğenenler",
    alternativesTitle: "Alternatifler",
    alternativeFaster: "Daha hızlı seçenek",
    alternativeLighter: "Daha hafif seçenek",
    alternativeBudget: "Daha ekonomik seçenek",
    cookCta: "Bu tarifi yapalım",
    swipeAgain: "Tekrar kaydır",
    missingIngredients: "Eksik malzemeler",
  },
  planner: {
    title: "Haftalık plan",
    subtitle: "Bir mod seç, AI haftanı kursun.",
    modeBusy: "Yoğun hafta",
    modeHealthy: "Sağlıklı hafta",
    modeBudget: "Ekonomik hafta",
    modeComfort: "Konfor yemekleri",
    modeKids: "Çocuk dostu",
    generate: "Planı oluştur",
    regenerateDay: "Bu günü yenile",
    groceryList: "Alışveriş listesi",
    days: ["Pzt", "Sal", "Çar", "Per", "Cum", "Cmt", "Paz"],
    dayLong: [
      "Pazartesi",
      "Salı",
      "Çarşamba",
      "Perşembe",
      "Cuma",
      "Cumartesi",
      "Pazar",
    ],
  },
  pantry: {
    title: "Kiler",
    subtitle: "Evdeki malzemeleri yaz, AI ayrıştırsın.",
    inputPlaceholder: "tavuk yoğurt patates yumurta domates…",
    parse: "Ayrıştır ve ekle",
    empty: "Henüz malzeme eklenmedi.",
    addedCount: (n: number) => `${n} malzeme eklendi`,
    suggestCta: "Bunlarla ne yapsam?",
    scanCta: "Fişten ekle",
    scanReading: "Fiş okunuyor…",
    scanEmpty: "Fişte malzeme bulamadım. Daha net bir fotoğraf dener misin?",
  },
  recipe: {
    ingredients: "Malzemeler",
    steps: "Yapılışı",
    prep: "Hazırlık",
    difficulty: "Zorluk",
    tags: "Etiketler",
    cookCta: "Pişirmeye başla",
    saveCta: "Kaydet",
    explainCta: "Bana göre uyarla",
  },
  profile: {
    title: "Profil",
    household: "Ev",
    members: "Üyeler",
    preferences: "Tercihler",
    allergies: "Alerjiler",
    dislikes: "Sevmediklerim",
    spice: "Acı toleransı",
    cuisines: "Sevdiğim mutfaklar",
    signOut: "Çıkış yap",
    invite: "Eşini davet et",
  },
  import: {
    title: "Tarif içe aktar",
    subtitle: "Instagram bağlantısı yapıştır ya da caption ekle.",
    linkPlaceholder: "https://instagram.com/p/…",
    captionPlaceholder: "Caption metnini yapıştır…",
    screenshot: "Ekran görüntüsü yükle (yakında)",
    importCta: "İçe aktar",
  },
} as const;

export type Copy = typeof t;
