import type { Cocktail, CocktailGlass, CocktailTechnique } from "@/types/bar";

/**
 * Hand-curated set of 12 internationally famous cocktails. Each entry uses
 * `BarIngredient.id` references from `barCatalog.ts` so the matcher can
 * compute cookability against the user's selected cabinet.
 *
 * Future Instagram-scraped recipes (Faz 4) will append to this list with
 * `source: "influencer"` while keeping the same shape.
 */
export const FAMOUS_COCKTAILS: Cocktail[] = [
  {
    id: "cocktail-negroni",
    name: "Negroni",
    altName: "Negroni",
    description:
      "Acımsı ve şık. Cin, Campari ve tatlı vermut'un eşit oranlı klasiği.",
    emoji: "🟥",
    technique: "stir",
    glass: "rocks",
    difficulty: "kolay",
    prepTimeMinutes: 3,
    servings: 1,
    ingredients: [
      { ingredientId: "spirit-gin", amount: "30 ml" },
      { ingredientId: "liqueur-campari", amount: "30 ml" },
      { ingredientId: "liqueur-vermouth-sweet", amount: "30 ml" },
      { ingredientId: "citrus-orange", amount: "1 dilim", optional: true },
    ],
    steps: [
      "Tüm sıvı malzemeleri buz dolu bir mixing glass'a koyun.",
      "Bir bar kaşığıyla 20-30 saniye karıştırın.",
      "Buz dolu rocks bardağa süzün.",
      "Portakal kabuğunu sıkıp bardağa atarak servis edin.",
    ],
    tags: ["klasik", "acımsı", "stir"],
    source: "classic",
  },
  {
    id: "cocktail-aperol-spritz",
    name: "Aperol Spritz",
    altName: "Aperol Spritz",
    description: "İtalyan yaz aperitifi. Hafif, kabarcıklı ve portakal kokulu.",
    emoji: "🧡",
    technique: "build",
    glass: "wine",
    difficulty: "kolay",
    prepTimeMinutes: 2,
    servings: 1,
    ingredients: [
      { ingredientId: "wine-prosecco", amount: "90 ml" },
      { ingredientId: "liqueur-aperol", amount: "60 ml" },
      { ingredientId: "mixer-soda", amount: "30 ml" },
      { ingredientId: "citrus-orange", amount: "1 dilim", optional: true },
    ],
    steps: [
      "Buzlu büyük bir şarap kadehine önce Prosecco'yu dökün.",
      "Üzerine Aperol'ü ekleyin.",
      "Sodayı yavaşça gezdirerek koyun, kabarcıkları kaybetmeyin.",
      "Portakal dilimiyle süsleyin.",
    ],
    tags: ["yaz", "aperitif", "düşük alkol"],
    source: "classic",
  },
  {
    id: "cocktail-margarita",
    name: "Margarita",
    altName: "Classic Margarita",
    description:
      "Tekila, taze misket limonu ve triple sec. Bardağın kenarı tuzlu.",
    emoji: "🍸",
    technique: "shake",
    glass: "coupe",
    difficulty: "kolay",
    prepTimeMinutes: 4,
    servings: 1,
    ingredients: [
      { ingredientId: "spirit-tequila", amount: "60 ml" },
      { ingredientId: "liqueur-triple-sec", amount: "30 ml" },
      { ingredientId: "citrus-lime", amount: "30 ml taze su" },
      { ingredientId: "garnish-salt", amount: "kenar için", optional: true },
    ],
    steps: [
      "Bardak ağzını limon dilimiyle ıslatıp tuza batırın.",
      "Tüm malzemeleri buz dolu shaker'a koyun.",
      "10-15 saniye sıkıca çalkalayın.",
      "Soğutulmuş bardağa süzerek servis edin.",
    ],
    tags: ["klasik", "shake", "ekşimsi"],
    source: "classic",
  },
  {
    id: "cocktail-mojito",
    name: "Mojito",
    altName: "Cuban Mojito",
    description: "Beyaz rom, taze nane, misket limonu ve sodanın ferahlığı.",
    emoji: "🌿",
    technique: "muddle",
    glass: "highball",
    difficulty: "kolay",
    prepTimeMinutes: 5,
    servings: 1,
    ingredients: [
      { ingredientId: "spirit-rum-white", amount: "60 ml" },
      { ingredientId: "garnish-mint", amount: "8-10 yaprak" },
      { ingredientId: "citrus-lime", amount: "1/2 adet" },
      { ingredientId: "sweet-simple-syrup", amount: "15 ml" },
      { ingredientId: "mixer-soda", amount: "tamamlamak için" },
    ],
    steps: [
      "Highball bardağa nane yapraklarını ve şurubu koyun, hafifçe ezin.",
      "Misket limonu suyunu ve romu ekleyin.",
      "Bardağı buzla doldurup sodayla tamamlayın.",
      "Uzun bir kaşıkla nazikçe karıştırın, nane dalıyla servis edin.",
    ],
    tags: ["yaz", "ferah", "muddle"],
    source: "classic",
  },
  {
    id: "cocktail-old-fashioned",
    name: "Old Fashioned",
    altName: "Old Fashioned",
    description:
      "Whiskey, şeker ve birkaç damla bitter. Kokteyl tarihinin köşe taşı.",
    emoji: "🥃",
    technique: "stir",
    glass: "rocks",
    difficulty: "orta",
    prepTimeMinutes: 4,
    servings: 1,
    ingredients: [
      { ingredientId: "spirit-bourbon", amount: "60 ml" },
      { ingredientId: "sweet-simple-syrup", amount: "7 ml" },
      { ingredientId: "bitter-angostura", amount: "2-3 damla" },
      { ingredientId: "citrus-orange", amount: "kabuk", optional: true },
    ],
    steps: [
      "Rocks bardağa şurup ve bitter'ı koyun.",
      "Büyük bir buz küpü atın, bourbon'u ekleyin.",
      "Bar kaşığıyla 20 saniye karıştırın.",
      "Portakal kabuğunu sıkıp bardağa atarak servis edin.",
    ],
    tags: ["klasik", "whiskey", "stir"],
    source: "classic",
  },
  {
    id: "cocktail-espresso-martini",
    name: "Espresso Martini",
    altName: "Espresso Martini",
    description:
      "Vodka, taze espresso ve kahve likörü — köpüklü ve şık bir uyarıcı.",
    emoji: "☕",
    technique: "shake",
    glass: "coupe",
    difficulty: "orta",
    prepTimeMinutes: 5,
    servings: 1,
    ingredients: [
      { ingredientId: "spirit-vodka", amount: "45 ml" },
      { ingredientId: "liqueur-coffee", amount: "15 ml" },
      { ingredientId: "mixer-espresso", amount: "30 ml taze" },
      { ingredientId: "sweet-simple-syrup", amount: "10 ml" },
    ],
    steps: [
      "Espresso'yu çekip biraz soğumasını bekleyin.",
      "Tüm malzemeleri buz dolu shaker'a koyun.",
      "Üstte kalıcı köpük için 15 saniye sert çalkalayın.",
      "Soğutulmuş coupe bardağa süzün.",
    ],
    tags: ["modern klasik", "shake", "kahve"],
    source: "classic",
  },
  {
    id: "cocktail-whiskey-sour",
    name: "Whiskey Sour",
    altName: "Whiskey Sour",
    description: "Bourbon, taze limon ve şurubun dengesi. Klasik ekşimsi.",
    emoji: "🍋",
    technique: "shake",
    glass: "rocks",
    difficulty: "kolay",
    prepTimeMinutes: 4,
    servings: 1,
    ingredients: [
      { ingredientId: "spirit-bourbon", amount: "60 ml" },
      { ingredientId: "citrus-lemon", amount: "30 ml taze su" },
      { ingredientId: "sweet-simple-syrup", amount: "20 ml" },
      { ingredientId: "garnish-cherry", amount: "1 adet", optional: true },
    ],
    steps: [
      "Tüm malzemeleri buz dolu shaker'a koyun.",
      "10 saniye sıkıca çalkalayın.",
      "Buz dolu rocks bardağa süzün.",
      "Vişne ve limon kabuğuyla süsleyin.",
    ],
    tags: ["klasik", "ekşimsi", "shake"],
    source: "classic",
  },
  {
    id: "cocktail-cosmopolitan",
    name: "Cosmopolitan",
    altName: "Cosmopolitan",
    description:
      "Vodka, triple sec, yaban mersini ve misket limonu. Pembe ve taze.",
    emoji: "💗",
    technique: "shake",
    glass: "martini",
    difficulty: "kolay",
    prepTimeMinutes: 4,
    servings: 1,
    ingredients: [
      { ingredientId: "spirit-vodka", amount: "45 ml" },
      { ingredientId: "liqueur-triple-sec", amount: "15 ml" },
      { ingredientId: "mixer-cranberry", amount: "30 ml" },
      { ingredientId: "citrus-lime", amount: "15 ml taze su" },
    ],
    steps: [
      "Tüm malzemeleri buz dolu shaker'a koyun.",
      "10 saniye sert çalkalayın.",
      "Soğutulmuş martini kadehine süzün.",
      "Portakal veya limon kabuğuyla servis edin.",
    ],
    tags: ["klasik", "shake", "meyveli"],
    source: "classic",
  },
  {
    id: "cocktail-manhattan",
    name: "Manhattan",
    altName: "Manhattan",
    description: "Rye whiskey, tatlı vermut ve Angostura. Cesur ve dengeli.",
    emoji: "🍒",
    technique: "stir",
    glass: "coupe",
    difficulty: "orta",
    prepTimeMinutes: 4,
    servings: 1,
    ingredients: [
      { ingredientId: "spirit-rye", amount: "60 ml" },
      { ingredientId: "liqueur-vermouth-sweet", amount: "30 ml" },
      { ingredientId: "bitter-angostura", amount: "2 damla" },
      { ingredientId: "garnish-cherry", amount: "1 adet", optional: true },
    ],
    steps: [
      "Tüm malzemeleri buz dolu mixing glass'a koyun.",
      "Bar kaşığıyla 30 saniye karıştırın.",
      "Soğutulmuş coupe kadehine süzün.",
      "Maraschino vişnesiyle süsleyin.",
    ],
    tags: ["klasik", "stir", "whiskey"],
    source: "classic",
  },
  {
    id: "cocktail-moscow-mule",
    name: "Moscow Mule",
    altName: "Moscow Mule",
    description: "Vodka, zencefil birası ve misket limonu — bakır kupada.",
    emoji: "🥒",
    technique: "build",
    glass: "copper-mug",
    difficulty: "kolay",
    prepTimeMinutes: 2,
    servings: 1,
    ingredients: [
      { ingredientId: "spirit-vodka", amount: "60 ml" },
      { ingredientId: "citrus-lime", amount: "15 ml taze su" },
      { ingredientId: "mixer-ginger-beer", amount: "120 ml" },
      { ingredientId: "garnish-mint", amount: "1 dal", optional: true },
    ],
    steps: [
      "Bakır kupayı buzla doldurun.",
      "Vodka ve misket limonu suyunu ekleyin.",
      "Üzerine soğuk zencefil birasını dökün.",
      "Hafifçe karıştırıp nane ve limon dilimiyle servis edin.",
    ],
    tags: ["yaz", "build", "ferah"],
    source: "classic",
  },
  {
    id: "cocktail-paloma",
    name: "Paloma",
    altName: "Paloma",
    description: "Tekila ve greyfurt sodası. Margarita'dan daha hafif, ferah.",
    emoji: "🍑",
    technique: "build",
    glass: "highball",
    difficulty: "kolay",
    prepTimeMinutes: 3,
    servings: 1,
    ingredients: [
      { ingredientId: "spirit-tequila", amount: "60 ml" },
      { ingredientId: "citrus-grapefruit", amount: "60 ml taze su" },
      { ingredientId: "citrus-lime", amount: "15 ml taze su" },
      { ingredientId: "mixer-soda", amount: "tamamlamak için" },
      { ingredientId: "garnish-salt", amount: "kenar için", optional: true },
    ],
    steps: [
      "Bardağın kenarını misket limonuyla ıslatıp tuza batırın.",
      "Bardağı buzla doldurun, tekila ve sitrüs sularını ekleyin.",
      "Sodayla tamamlayıp hafifçe karıştırın.",
      "Greyfurt dilimiyle süsleyin.",
    ],
    tags: ["yaz", "build", "tekila"],
    source: "classic",
  },
  {
    id: "cocktail-french-75",
    name: "French 75",
    altName: "French 75",
    description: "Cin, taze limon, şurup ve şampanyanın zarif buluşması.",
    emoji: "🥂",
    technique: "shake",
    glass: "flute",
    difficulty: "orta",
    prepTimeMinutes: 4,
    servings: 1,
    ingredients: [
      { ingredientId: "spirit-gin", amount: "30 ml" },
      { ingredientId: "citrus-lemon", amount: "15 ml taze su" },
      { ingredientId: "sweet-simple-syrup", amount: "10 ml" },
      { ingredientId: "wine-champagne", amount: "tamamlamak için" },
    ],
    steps: [
      "Cin, limon ve şurubu buz dolu shaker'a koyun.",
      "10 saniye çalkalayın.",
      "Soğuk şampanya kadehine süzün.",
      "Üzerine şampanyayı yavaşça döküp limon kabuğuyla servis edin.",
    ],
    tags: ["klasik", "köpüklü", "şık"],
    source: "classic",
  },
];

export const FAMOUS_COCKTAIL_INDEX: Record<string, Cocktail> =
  Object.fromEntries(FAMOUS_COCKTAILS.map((c) => [c.id, c]));

export const COCKTAIL_TECHNIQUE_LABEL: Record<CocktailTechnique, string> = {
  shake: "Shake",
  stir: "Stir",
  build: "Build",
  blend: "Blend",
  muddle: "Muddle",
};

export const COCKTAIL_GLASS_LABEL: Record<CocktailGlass, string> = {
  rocks: "Rocks glass",
  highball: "Highball glass",
  coupe: "Coupe",
  martini: "Martini glass",
  flute: "Champagne flute",
  wine: "Wine glass",
  "copper-mug": "Copper mug",
  hurricane: "Hurricane glass",
  tiki: "Tiki mug",
  "julep-cup": "Julep cup",
  mug: "Mug",
};
