import { Recipe } from "@/types/domain";

/**
 * Realistic Turkish household recipes — the meals families actually cook.
 * Imagery uses Unsplash placeholders for the MVP scaffold.
 */
export const MOCK_RECIPES: Recipe[] = [
  {
    id: "r-mercimek",
    title: "Mercimek Çorbası",
    description: "Klasik, sıcacık ve ev hissi veren kırmızı mercimek çorbası.",
    imageUrl:
      "https://images.unsplash.com/photo-1547592180-85f173990554?w=1200",
    prepTimeMinutes: 30,
    difficulty: "kolay",
    servings: 4,
    ingredients: [
      { name: "kırmızı mercimek", quantity: "1 su bardağı" },
      { name: "soğan", quantity: "1 adet" },
      { name: "havuç", quantity: "1 adet" },
      { name: "patates", quantity: "1 adet" },
      { name: "tereyağı", quantity: "1 yemek kaşığı" },
      { name: "kırmızı toz biber", quantity: "1 tatlı kaşığı" },
      { name: "tuz", quantity: "tadında" },
    ],
    steps: [
      "Soğan, havuç ve patatesi küçük doğra.",
      "Tencerede tereyağında soğanı pembeleştir.",
      "Mercimek ve sebzeleri ekle, üzerine sıcak su koy.",
      "Yumuşayana kadar 25 dk kısık ateşte pişir.",
      "Blendırdan geçir, üzerine kızdırılmış toz biberli yağ gez.",
    ],
    tags: ["çorba", "vejetaryen", "pratik"],
    cuisine: "Türk",
  },
  {
    id: "r-kuru-fasulye",
    title: "Kuru Fasulye",
    description: "Pilav üstü kuru fasulye — kalabalık sofraların vazgeçilmezi.",
    imageUrl:
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=1200",
    prepTimeMinutes: 60,
    difficulty: "orta",
    servings: 4,
    ingredients: [
      { name: "kuru fasulye", quantity: "2 su bardağı" },
      { name: "soğan", quantity: "1 adet" },
      { name: "salça", quantity: "1 yemek kaşığı" },
      { name: "sucuk", quantity: "opsiyonel" },
      { name: "zeytinyağı", quantity: "3 yemek kaşığı" },
    ],
    steps: [
      "Fasulyeleri bir gece önceden ıslat.",
      "Soğanı yağda kavur, salçayı ekle.",
      "Süzülmüş fasulyeyi ve sıcak suyu ekle.",
      "Yumuşayana kadar 45 dk pişir.",
      "Pilavla servis et.",
    ],
    tags: ["ana yemek", "aile", "klasik"],
    cuisine: "Türk",
  },
  {
    id: "r-tavuk-sote",
    title: "Tavuk Sote",
    description: "Renkli biberlerle hızlı bir akşam yemeği.",
    imageUrl:
      "https://images.unsplash.com/photo-1604908554007-b0db4cce6dba?w=1200",
    prepTimeMinutes: 25,
    difficulty: "kolay",
    servings: 3,
    ingredients: [
      { name: "tavuk göğsü", quantity: "500 g" },
      { name: "kırmızı biber", quantity: "1 adet" },
      { name: "yeşil biber", quantity: "1 adet" },
      { name: "soğan", quantity: "1 adet" },
      { name: "domates", quantity: "2 adet" },
      { name: "zeytinyağı", quantity: "2 yk" },
    ],
    steps: [
      "Tavuğu kuşbaşı doğrayıp yağda mühürle.",
      "Soğan ve biberleri ekle, 5 dk sote et.",
      "Doğranmış domatesi ekle, suyunu çekene kadar pişir.",
      "Tuz, karabiber ve maydanozla servis et.",
    ],
    tags: ["ana yemek", "tavuk", "pratik"],
    cuisine: "Türk",
  },
  {
    id: "r-menemen",
    title: "Menemen",
    description: "Kahvaltının ya da geç bir akşamın kurtarıcısı.",
    imageUrl:
      "https://images.unsplash.com/photo-1606756790138-261d2b21cd75?w=1200",
    prepTimeMinutes: 15,
    difficulty: "kolay",
    servings: 2,
    ingredients: [
      { name: "yumurta", quantity: "4 adet" },
      { name: "domates", quantity: "2 adet" },
      { name: "sivri biber", quantity: "2 adet" },
      { name: "tereyağı", quantity: "1 yk" },
    ],
    steps: [
      "Biberleri tereyağında kavur.",
      "Soyulmuş domatesi ekle, suyunu çekene kadar pişir.",
      "Yumurtaları kır, yavaşça karıştır.",
      "Tuz ve karabiberle servis et.",
    ],
    tags: ["kahvaltı", "vejetaryen", "pratik"],
    cuisine: "Türk",
  },
  {
    id: "r-makarna",
    title: "Tereyağlı Makarna",
    description: "Hızlı, doyurucu ve herkesin sevdiği klasik.",
    imageUrl:
      "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=1200",
    prepTimeMinutes: 15,
    difficulty: "kolay",
    servings: 2,
    ingredients: [
      { name: "makarna", quantity: "250 g" },
      { name: "tereyağı", quantity: "2 yk" },
      { name: "kaşar peyniri", quantity: "rendelenmiş" },
    ],
    steps: [
      "Makarnayı tuzlu suda haşla.",
      "Süzdükten sonra tereyağıyla harmanla.",
      "Üzerine rendelenmiş kaşar serp.",
    ],
    tags: ["ana yemek", "pratik", "çocuk dostu"],
    cuisine: "İtalyan-Türk",
  },
  {
    id: "r-firinda-kofte",
    title: "Fırında Köfte Patates",
    description: "Tek tepside aile yemeği.",
    imageUrl:
      "https://images.unsplash.com/photo-1565895405138-6c3a1555da6a?w=1200",
    prepTimeMinutes: 50,
    difficulty: "orta",
    servings: 4,
    ingredients: [
      { name: "kıyma", quantity: "500 g" },
      { name: "patates", quantity: "3 adet" },
      { name: "domates", quantity: "2 adet" },
      { name: "biber", quantity: "2 adet" },
      { name: "salça", quantity: "1 yk" },
    ],
    steps: [
      "Kıymayı baharatla yoğur, köfte şekli ver.",
      "Sebzeleri ve köfteleri tepsiye diz.",
      "Salçalı sıcak suyu üzerine dök.",
      "180°C fırında 40 dk pişir.",
    ],
    tags: ["ana yemek", "aile", "fırın"],
    cuisine: "Türk",
  },
  {
    id: "r-yayla",
    title: "Yayla Çorbası",
    description: "Yoğurtlu, naneli, ferah bir çorba.",
    imageUrl:
      "https://images.unsplash.com/photo-1607330289024-1535c6b4e1c1?w=1200",
    prepTimeMinutes: 30,
    difficulty: "kolay",
    servings: 4,
    ingredients: [
      { name: "yoğurt", quantity: "2 su bardağı" },
      { name: "pirinç", quantity: "1/2 su bardağı" },
      { name: "yumurta sarısı", quantity: "1 adet" },
      { name: "kuru nane", quantity: "1 tk" },
      { name: "tereyağı", quantity: "1 yk" },
    ],
    steps: [
      "Pirinci suda haşla.",
      "Yoğurt, un ve yumurtayı çırp, çorbaya temperle.",
      "Üzerine naneli tereyağı gez.",
    ],
    tags: ["çorba", "vejetaryen"],
    cuisine: "Türk",
  },
  {
    id: "r-kabak-mucver",
    title: "Kabak Mücver",
    description: "Yoğurtla muhteşem, hafif bir akşam yemeği.",
    imageUrl:
      "https://images.unsplash.com/photo-1604908177522-401b1c364c5b?w=1200",
    prepTimeMinutes: 25,
    difficulty: "kolay",
    servings: 3,
    ingredients: [
      { name: "kabak", quantity: "2 adet" },
      { name: "yumurta", quantity: "2 adet" },
      { name: "un", quantity: "3 yk" },
      { name: "beyaz peynir", quantity: "100 g" },
      { name: "dereotu", quantity: "bir tutam" },
    ],
    steps: [
      "Kabağı rendele, suyunu sık.",
      "Tüm malzemeleri karıştır.",
      "Kaşıkla yağa al, kızart.",
    ],
    tags: ["vejetaryen", "hafif"],
    cuisine: "Türk",
  },
  {
    id: "r-zeytinyagli-fasulye",
    title: "Zeytinyağlı Taze Fasulye",
    description: "Soğuk servis edilen, ferah bir klasik.",
    imageUrl:
      "https://images.unsplash.com/photo-1604908554007-1c1f1d7b9e7f?w=1200",
    prepTimeMinutes: 40,
    difficulty: "kolay",
    servings: 4,
    ingredients: [
      { name: "taze fasulye", quantity: "500 g" },
      { name: "soğan", quantity: "1 adet" },
      { name: "domates", quantity: "1 adet" },
      { name: "zeytinyağı", quantity: "4 yk" },
      { name: "şeker", quantity: "1 tk" },
    ],
    steps: [
      "Soğanı yağda kavur.",
      "Fasulyeyi ekle, kısaca çevir.",
      "Domates, şeker ve sıcak su ekle.",
      "Kısık ateşte yumuşayana kadar pişir, soğuk servis et.",
    ],
    tags: ["zeytinyağlı", "vejetaryen", "hafif"],
    cuisine: "Türk",
  },
  {
    id: "r-pilav",
    title: "Tereyağlı Şehriyeli Pilav",
    description: "Her yemeğin yanına yakışan klasik.",
    imageUrl:
      "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=1200",
    prepTimeMinutes: 25,
    difficulty: "kolay",
    servings: 4,
    ingredients: [
      { name: "pirinç", quantity: "2 su bardağı" },
      { name: "tel şehriye", quantity: "1/2 su bardağı" },
      { name: "tereyağı", quantity: "2 yk" },
      { name: "tuz", quantity: "1 tk" },
    ],
    steps: [
      "Şehriyeyi tereyağında pembeleştir.",
      "Yıkanmış pirinci ekle, kısaca kavur.",
      "Sıcak suyu ekle, tuzla, kapağı kapatıp kısık ateşte pişir.",
      "10 dk demlendir.",
    ],
    tags: ["yan yemek", "klasik"],
    cuisine: "Türk",
  },
  {
    id: "r-sucuklu-yumurta",
    title: "Sucuklu Yumurta",
    description: "Kahvaltıların kralı.",
    imageUrl:
      "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=1200",
    prepTimeMinutes: 10,
    difficulty: "kolay",
    servings: 2,
    ingredients: [
      { name: "sucuk", quantity: "6 dilim" },
      { name: "yumurta", quantity: "3 adet" },
      { name: "tereyağı", quantity: "1 tk" },
    ],
    steps: [
      "Sucukları sahanda kızart.",
      "Yumurtaları kır, sarısı akışkan kalacak şekilde pişir.",
    ],
    tags: ["kahvaltı", "pratik"],
    cuisine: "Türk",
  },
  {
    id: "r-imam-bayildi",
    title: "İmam Bayıldı",
    description: "Zeytinyağlı, doyurucu, ev sofrasının ışığı.",
    imageUrl:
      "https://images.unsplash.com/photo-1626078297007-1e8b3a5c79b1?w=1200",
    prepTimeMinutes: 55,
    difficulty: "orta",
    servings: 4,
    ingredients: [
      { name: "patlıcan", quantity: "4 adet" },
      { name: "soğan", quantity: "2 adet" },
      { name: "domates", quantity: "2 adet" },
      { name: "sarımsak", quantity: "4 diş" },
      { name: "zeytinyağı", quantity: "5 yk" },
    ],
    steps: [
      "Patlıcanları alaca soyup tuzlu suda beklet.",
      "İç harcı için soğan, sarımsak ve domatesi pişir.",
      "Patlıcanları hafif kızart, içini doldur.",
      "Tencerede zeytinyağı ve suyla 30 dk pişir.",
    ],
    tags: ["zeytinyağlı", "vejetaryen"],
    cuisine: "Türk",
  },
  {
    id: "r-mantarli-milfoy-tart",
    title: "Mantarlı Milföy Tart",
    description:
      "Çıtır milföy üzerinde mantarlı, aromatik ve pratik bir fırın lezzeti.",
    imageUrl:
      "https://images.unsplash.com/photo-1565299543923-37dd37887442?w=1200",
    prepTimeMinutes: 45,
    difficulty: "orta",
    servings: 4,
    ingredients: [
      { name: "milföy", quantity: "9 adet" },
      { name: "mantar", quantity: "400 gr" },
      { name: "soğan", quantity: "2 adet" },
      { name: "tereyağı", quantity: "2 yk" },
      { name: "yumurta sarısı", quantity: "1 adet" },
    ],
    steps: [
      "Mantar ve soğanı tavada sotele.",
      "Milföyleri fırın tepsisine yerleştir.",
      "Mantarlı harcı milföyün üzerine yay.",
      "Üzerini yumurta sarısıyla fırçala ve kızarana kadar pişir.",
    ],
    tags: ["hamurlu", "fırın", "vejetaryen", "mantar"],
    cuisine: "Türk",
  },
  {
    id: "r-zeytinyagli-kabak-siyirma",
    title: "Zeytinyağlı Kabak Sıyırma",
    description:
      "Hafif, ferah ve yaz sofralarına uygun zeytinyağlı kabak yemeği.",
    imageUrl:
      "https://images.unsplash.com/photo-1598511757337-fe2cafc31ba0?w=1200",
    prepTimeMinutes: 35,
    difficulty: "kolay",
    servings: 4,
    ingredients: [
      { name: "kabak", quantity: "2 adet" },
      { name: "soğan", quantity: "1 adet" },
      { name: "pirinç", quantity: "1/4 su bardağı" },
      { name: "zeytinyağı", quantity: "1 su bardağı" },
      { name: "limon", quantity: "1 adet" },
    ],
    steps: [
      "Soğanı zeytinyağında yumuşayana kadar pişir.",
      "Pirinci ekleyip kısa süre çevir.",
      "İnce doğranmış kabakları ekle.",
      "Limon suyu ve yeşilliklerle tamamlayıp soğuk servis et.",
    ],
    tags: ["zeytinyağlı", "vejetaryen", "hafif", "sebze"],
    cuisine: "Türk",
  },
  {
    id: "r-girit-ezmeli-borek",
    title: "Girit Ezmeli Börek",
    description:
      "Peynirli ve fesleğenli iç harcıyla doyurucu, özel sofralık bir börek.",
    imageUrl:
      "https://images.unsplash.com/photo-1612392061787-2d078b3e573d?w=1200",
    prepTimeMinutes: 60,
    difficulty: "orta",
    servings: 6,
    ingredients: [
      { name: "yufka", quantity: "3 adet" },
      { name: "yoğurt", quantity: "1 su bardağı" },
      { name: "zeytinyağı", quantity: "1/2 su bardağı" },
      { name: "beyaz peynir", quantity: "250 gr" },
      { name: "lor peyniri", quantity: "250 gr" },
    ],
    steps: [
      "Peynirleri ezip yeşilliklerle karıştır.",
      "Yufkaları soslayarak üst üste diz.",
      "İç harcı yayıp böreği şekillendir.",
      "Fırında üzeri kızarana kadar pişir.",
    ],
    tags: ["börek", "hamurlu", "peynirli", "kahvaltı"],
    cuisine: "Türk",
  },
  {
    id: "r-bademli-kabak-tarator",
    title: "Bademli Kabak Tarator",
    description: "Yoğurtlu, kabaklı ve bademli ferah bir meze alternatifi.",
    imageUrl:
      "https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=1200",
    prepTimeMinutes: 25,
    difficulty: "kolay",
    servings: 4,
    ingredients: [
      { name: "kabak", quantity: "2 adet" },
      { name: "süzme yoğurt", quantity: "1.5 su bardağı" },
      { name: "sarımsak", quantity: "1 diş" },
      { name: "zeytinyağı", quantity: "2 yk" },
      { name: "file badem", quantity: "1 avuç" },
    ],
    steps: [
      "Kabakları rendeleyip tavada sotele.",
      "Yoğurt, sarımsak ve tuzu karıştır.",
      "Soğuyan kabağı yoğurtlu karışıma ekle.",
      "Üzerine kavrulmuş badem serpip servis et.",
    ],
    tags: ["meze", "yoğurtlu", "vejetaryen", "hafif"],
    cuisine: "Türk",
  },
  {
    id: "r-cilekli-semizotu-salatasi",
    title: "Çilekli Semizotu Salatası",
    description: "Tatlı-ekşi dengesiyle farklı, ferah ve hafif bir salata.",
    imageUrl:
      "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=1200",
    prepTimeMinutes: 15,
    difficulty: "kolay",
    servings: 4,
    ingredients: [
      { name: "semizotu", quantity: "2 bağ" },
      { name: "çilek", quantity: "10 adet" },
      { name: "ceviz", quantity: "1 su bardağı" },
      { name: "zeytinyağı", quantity: "6 yk" },
      { name: "limon suyu", quantity: "1/4 limon" },
    ],
    steps: [
      "Semizotunu ayıklayıp yıka.",
      "Çilekleri dilimle, cevizi iri parçala.",
      "Sos malzemelerini karıştır.",
      "Tüm malzemeleri harmanlayıp servis et.",
    ],
    tags: ["salata", "hafif", "vejetaryen", "pratik"],
    cuisine: "Türk",
  },
  {
    id: "r-beef-wellington",
    title: "Beef Wellington",
    description:
      "Milföy kaplı bonfileyle hazırlanan gösterişli ve özel günlere uygun bir ana yemek.",
    imageUrl:
      "https://images.unsplash.com/photo-1558030006-450675393462?w=1200",
    prepTimeMinutes: 90,
    difficulty: "zor",
    servings: 4,
    ingredients: [
      { name: "bonfile", quantity: "700 gr" },
      { name: "milföy", quantity: "5 adet" },
      { name: "mantar", quantity: "10 adet" },
      { name: "sarımsak", quantity: "2 diş" },
      { name: "yumurta sarısı", quantity: "1 adet" },
    ],
    steps: [
      "Bonfileyi tavada mühürle.",
      "Mantar harcını hazırlayıp soğut.",
      "Eti milföy ve mantarlı harçla sar.",
      "Üzerini yumurta sarısıyla fırçala ve fırında pişir.",
    ],
    tags: ["et", "özel gün", "fırın", "dünya mutfağı"],
    cuisine: "İngiliz",
  },
  {
    id: "r-cikolata-mus-tiramisu",
    title: "Çikolata Mus Tiramisu",
    description:
      "Kahve ve çikolata sevenler için yoğun aromalı, katmanlı bir tatlı.",
    imageUrl:
      "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=1200",
    prepTimeMinutes: 50,
    difficulty: "orta",
    servings: 6,
    ingredients: [
      { name: "kedidili", quantity: "1 paket" },
      { name: "granül kahve", quantity: "2 yk" },
      { name: "bitter çikolata", quantity: "290 gr" },
      { name: "yumurta", quantity: "4 adet" },
      { name: "krema", quantity: "1 su bardağı" },
    ],
    steps: [
      "Kahveli karışımı hazırla.",
      "Çikolatalı mus katmanını hazırla.",
      "Kedidillerini kahveyle ıslat.",
      "Katmanları oluşturup buzdolabında dinlendir.",
    ],
    tags: ["tatlı", "çikolatalı", "kahveli", "özel gün"],
    cuisine: "İtalyan",
  },
  {
    id: "r-isvec-keki-kladdkaka",
    title: "İsveç Keki - Kladdkaka",
    description: "Dışı hafif pişmiş, içi yoğun çikolatalı pratik bir kek.",
    imageUrl:
      "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=1200",
    prepTimeMinutes: 40,
    difficulty: "orta",
    servings: 6,
    ingredients: [
      { name: "tereyağı", quantity: "200 gr" },
      { name: "bitter çikolata", quantity: "200 gr" },
      { name: "toz şeker", quantity: "250 gr" },
      { name: "yumurta", quantity: "4 adet" },
      { name: "un", quantity: "40 gr" },
    ],
    steps: [
      "Tereyağı ve çikolatayı erit.",
      "Yumurta ve şekeri karıştır.",
      "Unu ekleyip kısa süre karıştır.",
      "Kalıba alıp içi hafif nemli kalacak şekilde pişir.",
    ],
    tags: ["tatlı", "kek", "çikolatalı", "dünya mutfağı"],
    cuisine: "İsveç",
  },
  {
    id: "r-muzlu-ters-yuz-pasta",
    title: "Muzlu Ters Yüz Pasta",
    description:
      "Karamelli muz tabanı ve yumuşak kek dokusuyla keyifli bir ev tatlısı.",
    imageUrl:
      "https://images.unsplash.com/photo-1606101273945-e9eba91c0dc4?w=1200",
    prepTimeMinutes: 65,
    difficulty: "orta",
    servings: 8,
    ingredients: [
      { name: "muz", quantity: "7 adet" },
      { name: "toz şeker", quantity: "1 su bardağı" },
      { name: "tereyağı", quantity: "125 gr" },
      { name: "yumurta", quantity: "2 adet" },
      { name: "un", quantity: "2 su bardağı" },
    ],
    steps: [
      "Karamel tabanı hazırla.",
      "Muzları kalıba diz.",
      "Kek harcını karıştır.",
      "Harcı muzların üzerine döküp fırında pişir.",
    ],
    tags: ["tatlı", "kek", "muzlu", "comfort_food"],
    cuisine: "Dünya",
  },
];

export const findRecipe = (id: string): Recipe | undefined =>
  MOCK_RECIPES.find((r) => r.id === id);
