/* eslint-disable no-console */
/**
 * Generates supabase/seed.sql from src/constants/mockRecipes.ts.
 *
 *   npx tsx scripts/generate-seed.ts
 *
 * Run after editing the recipe catalogue, then either:
 *   - paste the file contents into the Supabase SQL editor, or
 *   - `supabase db reset` after `supabase/seed.sql` is in place.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { MOCK_RECIPES } from "../src/constants/mockRecipes";

function sqlEscape(s: string): string {
  return s.replace(/'/g, "''");
}

function quote(s: string): string {
  return `'${sqlEscape(s)}'`;
}

function textArray(items: string[]): string {
  if (!items.length) return "ARRAY[]::text[]";
  return `ARRAY[${items.map(quote).join(", ")}]`;
}

const header = `-- Auto-generated by scripts/generate-seed.ts. Do not edit by hand.
-- Seeds the public.recipes table with the SwipeBite mock catalogue.

set check_function_bodies = off;

`;

const rows = MOCK_RECIPES.map((r) => {
  const ingredientsJson = JSON.stringify(r.ingredients).replace(/'/g, "''");
  // Use a stable UUID v5-ish derived from id slug.
  // Easiest: let Postgres generate one — we delete-then-insert with title as natural key.
  return `insert into public.recipes (
  title, description, image_url, prep_time_minutes, difficulty,
  servings, ingredients, steps, tags, cuisine
)
select ${quote(r.title)}, ${quote(r.description)}, ${quote(r.imageUrl)}, ${r.prepTimeMinutes}, ${quote(r.difficulty)},
       ${r.servings}, '${ingredientsJson}'::jsonb, ${textArray(r.steps)}, ${textArray(r.tags)}, ${quote(r.cuisine)}
where not exists (select 1 from public.recipes where title = ${quote(r.title)});`;
}).join("\n\n");

const out = header + rows + "\n";
const path = resolve(process.cwd(), "supabase/seed.sql");
writeFileSync(path, out, "utf8");
console.log(`Wrote ${MOCK_RECIPES.length} recipes → ${path}`);
